const vocabulary = [
  {
    "id": "Yes",
    "level": 0,
    "parent": null,
    "english": "Yes",
    "bulgarian": "Да",
    "image": "images/yes.png",
    "audio": "audio/Да.mp3",
    "hasChildren": false,
    "order": 1
  },
  {
    "id": "No",
    "level": 0,
    "parent": null,
    "english": "No",
    "bulgarian": "Не",
    "image": "images/no.png",
    "audio": "audio/Не.mp3",
    "hasChildren": false,
    "order": 2
  },
  {
    "id": "Help",
    "level": 0,
    "parent": null,
    "english": "Help",
    "bulgarian": "Помощ",
    "image": "images/help.png",
    "audio": "audio/Помощ.mp3",
    "hasChildren": false,
    "order": 3
  },
  {
    "id": "Family",
    "level": 0,
    "parent": null,
    "english": "Family",
    "bulgarian": "Семейство",
    "image": "images/family.png",
    "audio": "audio/Семейство.mp3",
    "hasChildren": true,
    "order": 4
  },
  {
    "id": "Mom",
    "level": 1,
    "parent": "Family",
    "english": "Mom",
    "bulgarian": "Мама",
    "image": "images/Mom.png",
    "audio": "audio/Мама.mp3",
    "hasChildren": false,
    "order": 5
  },
  {
    "id": "Dad",
    "level": 1,
    "parent": "Family",
    "english": "Dad",
    "bulgarian": "Татко",
    "image": "images/dad.png",
    "audio": "audio/Татко.mp3",
    "hasChildren": false,
    "order": 6
  },
  {
    "id": "Grandma",
    "level": 1,
    "parent": "Family",
    "english": "Grandma",
    "bulgarian": "Баба",
    "image": "images/grandma.png",
    "audio": "audio/Баба.mp3",
    "hasChildren": false,
    "order": 7
  },
  {
    "id": "Grandpa",
    "level": 1,
    "parent": "Family",
    "english": "Grandpa",
    "bulgarian": "Дядо",
    "image": "images/grandpa.png",
    "audio": "audio/Дядо.mp3",
    "hasChildren": false,
    "order": 8
  },
  {
    "id": "Home",
    "level": 1,
    "parent": "Family",
    "english": "Home",
    "bulgarian": "Дом",
    "image": "images/home.png",
    "audio": "audio/Дом.mp3",
    "hasChildren": false,
    "order": 9
  },
  {
    "id": "Aunt Peyton",
    "level": 1,
    "parent": "Family",
    "english": "Aunt Peyton",
    "bulgarian": "Леля Пейтън",
    "image": "images/Auntpeyton.png",
    "audio": "audio/Леля Пейтън.mp3",
    "hasChildren": false,
    "order": 10
  },
  {
    "id": "Uncle Addie",
    "level": 1,
    "parent": "Family",
    "english": "Uncle Addie",
    "bulgarian": "Чичо Ади",
    "image": "images/uncleaddie.png",
    "audio": "audio/Чичо Ади.mp3",
    "hasChildren": false,
    "order": 11
  },
  {
    "id": "Uncle Jasce",
    "level": 1,
    "parent": "Family",
    "english": "Uncle Jasce",
    "bulgarian": "Чичо Джейс",
    "image": "images/unclejasce.png",
    "audio": "audio/Чичо Джейс.mp3",
    "hasChildren": false,
    "order": 12
  },
  {
    "id": "Neighbors",
    "level": 1,
    "parent": "Family",
    "english": "Neighbors",
    "bulgarian": "Съседи",
    "image": "images/neighbors.png",
    "audio": "audio/Съседи.mp3",
    "hasChildren": false,
    "order": 13
  },
  {
    "id": "Baby",
    "level": 1,
    "parent": "Family",
    "english": "Baby",
    "bulgarian": "Бебе",
    "image": "images/baby.png",
    "audio": "audio/Бебе.mp3",
    "hasChildren": false,
    "order": 14
  },
  {
    "id": "Feelings",
    "level": 0,
    "parent": null,
    "english": "Feelings",
    "bulgarian": "Чувства",
    "image": "images/feelings.png",
    "audio": "audio/Чувства.mp3",
    "hasChildren": true,
    "order": 15
  },
  {
    "id": "Happy",
    "level": 1,
    "parent": "Feelings",
    "english": "Happy",
    "bulgarian": "Щастлив",
    "image": "images/happy.png",
    "audio": "audio/Щастлив.mp3",
    "hasChildren": false,
    "order": 16
  },
  {
    "id": "Sad",
    "level": 1,
    "parent": "Feelings",
    "english": "Sad",
    "bulgarian": "Тъжен",
    "image": "images/sad.png",
    "audio": "audio/Тъжен.mp3",
    "hasChildren": false,
    "order": 17
  },
  {
    "id": "Angry",
    "level": 1,
    "parent": "Feelings",
    "english": "Angry",
    "bulgarian": "Ядосан",
    "image": "images/angry.png",
    "audio": "audio/Ядосан.mp3",
    "hasChildren": false,
    "order": 18
  },
  {
    "id": "Tired",
    "level": 1,
    "parent": "Feelings",
    "english": "Tired",
    "bulgarian": "Уморен",
    "image": "images/tired.png",
    "audio": "audio/Уморен.mp3",
    "hasChildren": false,
    "order": 19
  },
  {
    "id": "Scared",
    "level": 1,
    "parent": "Feelings",
    "english": "Scared",
    "bulgarian": "Уплашен",
    "image": "images/scared.png",
    "audio": "audio/Уплашен.mp3",
    "hasChildren": false,
    "order": 20
  },
  {
    "id": "Confused",
    "level": 1,
    "parent": "Feelings",
    "english": "Confused",
    "bulgarian": "Объркан",
    "image": "images/confused.png",
    "audio": "audio/Объркан.mp3",
    "hasChildren": false,
    "order": 21
  },
  {
    "id": "Silly",
    "level": 1,
    "parent": "Feelings",
    "english": "Silly",
    "bulgarian": "Глупав",
    "image": "images/silly.png",
    "audio": "audio/Глупав.mp3",
    "hasChildren": false,
    "order": 22
  },
  {
    "id": "Disgust",
    "level": 1,
    "parent": "Feelings",
    "english": "Disgust",
    "bulgarian": "Отвращение",
    "image": "images/disgust.png",
    "audio": "audio/Отвращение.mp3",
    "hasChildren": false,
    "order": 23
  },
  {
    "id": "Needs",
    "level": 0,
    "parent": null,
    "english": "Needs",
    "bulgarian": "Нуждае се",
    "image": "images/needs.png",
    "audio": "audio/Нуждае.mp3",
    "hasChildren": true,
    "order": 24
  },
  {
    "id": "Hungry",
    "level": 1,
    "parent": "Needs",
    "english": "Hungry",
    "bulgarian": "Гладен",
    "image": "images/hungry.png",
    "audio": "audio/Гладен.mp3",
    "hasChildren": false,
    "order": 25
  },
  {
    "id": "Thirsty",
    "level": 1,
    "parent": "Needs",
    "english": "Thirsty",
    "bulgarian": "Жаден",
    "image": "images/thirsty.png",
    "audio": "audio/Жаден.mp3",
    "hasChildren": false,
    "order": 26
  },
  {
    "id": "Hurts",
    "level": 1,
    "parent": "Needs",
    "english": "Hurts",
    "bulgarian": "Боли",
    "image": "images/hurts.png",
    "audio": "audio/Боли.mp3",
    "hasChildren": false,
    "order": 27
  },
  {
    "id": "Bathroom",
    "level": 1,
    "parent": "Needs",
    "english": "Bathroom",
    "bulgarian": "Баня",
    "image": "images/bathroom.png",
    "audio": "audio/Баня.mp3",
    "hasChildren": false,
    "order": 28
  },
  {
    "id": "Pee",
    "level": 2,
    "parent": "bathroom",
    "english": "Pee",
    "bulgarian": "Пиш",
    "image": "images/pee.png",
    "audio": "audio/Пиш.mp3",
    "hasChildren": false,
    "order": 29
  },
  {
    "id": "Poop",
    "level": 2,
    "parent": "bathroom",
    "english": "Poop",
    "bulgarian": "Ака",
    "image": "images/poop.png",
    "audio": "audio/Ака.mp3",
    "hasChildren": false,
    "order": 30
  },
  {
    "id": "Clean",
    "level": 1,
    "parent": "Needs",
    "english": "Clean",
    "bulgarian": "Чист",
    "image": "images/clean.png",
    "audio": "audio/Чист.mp3",
    "hasChildren": true,
    "order": 31
  },
  {
    "id": "Bath",
    "level": 2,
    "parent": "Clean",
    "english": "Bath",
    "bulgarian": "Вана",
    "image": "images/bath.png",
    "audio": "audio/Вана.mp3",
    "hasChildren": false,
    "order": 32
  },
  {
    "id": "Hands",
    "level": 2,
    "parent": "Clean",
    "english": "Hands",
    "bulgarian": "Ръце",
    "image": "images/hands.png",
    "audio": "audio/Ръце.mp3",
    "hasChildren": false,
    "order": 33
  },
  {
    "id": "Teeth",
    "level": 2,
    "parent": "Clean",
    "english": "Teeth",
    "bulgarian": "Зъби",
    "image": "images/teeth.png",
    "audio": "audio/Зъби.mp3",
    "hasChildren": false,
    "order": 34
  },
  {
    "id": "Dirty",
    "level": 1,
    "parent": "Needs",
    "english": "Dirty",
    "bulgarian": "Мръсен",
    "image": "images/dirty.png",
    "audio": "audio/Мръсен.mp3",
    "hasChildren": false,
    "order": 35
  },
  {
    "id": "Sick",
    "level": 1,
    "parent": "Needs",
    "english": "Sick",
    "bulgarian": "Болен",
    "image": "images/sick.png",
    "audio": "audio/Болен.mp3",
    "hasChildren": false,
    "order": 36
  },
  {
    "id": "Bed",
    "level": 1,
    "parent": "Needs",
    "english": "Bed",
    "bulgarian": "Легло",
    "image": "images/Bed.png",
    "audio": "audio/Легло.mp3",
    "hasChildren": false,
    "order": 37
  },
  {
    "id": "Sleepy",
    "level": 1,
    "parent": "Needs",
    "english": "Sleepy",
    "bulgarian": "Сънлив",
    "image": "images/sleepy.png",
    "audio": "audio/Сънлив.mp3",
    "hasChildren": false,
    "order": 38
  },
  {
    "id": "Food",
    "level": 0,
    "parent": null,
    "english": "Food",
    "bulgarian": "Храна",
    "image": "images/food.png",
    "audio": "audio/Храна.mp3",
    "hasChildren": true,
    "order": 39
  },
  {
    "id": "Drinks",
    "level": 1,
    "parent": "Food",
    "english": "Drinks",
    "bulgarian": "Напитки",
    "image": "images/drinks.png",
    "audio": "audio/Напитки.mp3",
    "hasChildren": true,
    "order": 40
  },
  {
    "id": "Water",
    "level": 2,
    "parent": "Drinks",
    "english": "Water",
    "bulgarian": "вода",
    "image": "images/water.png",
    "audio": "audio/вода.mp3",
    "hasChildren": false,
    "order": 41
  },
  {
    "id": "Chocolate Milk",
    "level": 2,
    "parent": "Drinks",
    "english": "Chocolate Milk",
    "bulgarian": "Шоколадово мляко",
    "image": "images/chocolatemilk.png",
    "audio": "audio/Шоколадово мляко.mp3",
    "hasChildren": false,
    "order": 42
  },
  {
    "id": "Juice",
    "level": 2,
    "parent": "Drinks",
    "english": "Juice",
    "bulgarian": "Сок",
    "image": "images/juice.png",
    "audio": "audio/Сок.mp3",
    "hasChildren": false,
    "order": 43
  },
  {
    "id": "Apple",
    "level": 3,
    "parent": "Fruit",
    "english": "Apple",
    "bulgarian": "Ябълка",
    "image": "images/apple.png",
    "audio": "audio/Ябълка.mp3",
    "hasChildren": false,
    "order": 44
  },
  {
    "id": "Orange",
    "level": 3,
    "parent": "Fruit",
    "english": "Orange",
    "bulgarian": "Портокал",
    "image": "images/orange.png",
    "audio": "audio/Портокал.mp3",
    "hasChildren": false,
    "order": 45
  },
  {
    "id": "Milk",
    "level": 2,
    "parent": "Drinks",
    "english": "Milk",
    "bulgarian": "Мляко",
    "image": "images/milk.png",
    "audio": "audio/Мляко.mp3",
    "hasChildren": false,
    "order": 46
  },
  {
    "id": "Cereal",
    "level": 1,
    "parent": "Food",
    "english": "Cereal",
    "bulgarian": "Зърнена закуска",
    "image": "images/cereal.png",
    "audio": "audio/Зърнена закуска.mp3",
    "hasChildren": false,
    "order": 47
  },
  {
    "id": "Fruit",
    "level": 1,
    "parent": "Food",
    "english": "Fruit",
    "bulgarian": "Плод",
    "image": "images/fruit.png",
    "audio": "audio/Плод.mp3",
    "hasChildren": true,
    "order": 48
  },
  {
    "id": "Pizza",
    "level": 1,
    "parent": "Food",
    "english": "Pizza",
    "bulgarian": "Пица",
    "image": "images/pizza.png",
    "audio": "audio/Пица.mp3",
    "hasChildren": false,
    "order": 49
  },
  {
    "id": "Apple",
    "level": 2,
    "parent": "Fruit",
    "english": "Apple",
    "bulgarian": "Ябълка",
    "image": "images/apple.png",
    "audio": "audio/Ябълка.mp3",
    "hasChildren": false,
    "order": 50
  },
  {
    "id": "Banana",
    "level": 2,
    "parent": "Fruit",
    "english": "Banana",
    "bulgarian": "Банан",
    "image": "images/banana.png",
    "audio": "audio/Банан.mp3",
    "hasChildren": false,
    "order": 51
  },
  {
    "id": "Orange",
    "level": 2,
    "parent": "Fruit",
    "english": "Orange",
    "bulgarian": "Портокал",
    "image": "images/orange.png",
    "audio": "audio/Портокал.mp3",
    "hasChildren": false,
    "order": 52
  },
  {
    "id": "Strawberry",
    "level": 2,
    "parent": "Fruit",
    "english": "Strawberry",
    "bulgarian": "Ягода",
    "image": "images/Strawberry.png",
    "audio": "audio/Ягода.mp3",
    "hasChildren": false,
    "order": 53
  },
  {
    "id": "Watermelon",
    "level": 2,
    "parent": "Fruit",
    "english": "Watermelon",
    "bulgarian": "Диня",
    "image": "images/watermelon.png",
    "audio": "audio/Диня.mp3",
    "hasChildren": false,
    "order": 54
  },
  {
    "id": "Directions",
    "level": 0,
    "parent": null,
    "english": "Directions",
    "bulgarian": "Указания",
    "image": "images/directions.png",
    "audio": "audio/Указания.mp3",
    "hasChildren": true,
    "order": 55
  },
  {
    "id": "Up",
    "level": 1,
    "parent": "Directions",
    "english": "Up",
    "bulgarian": "Горе",
    "image": "images/up.png",
    "audio": "audio/Горе.mp3",
    "hasChildren": false,
    "order": 56
  },
  {
    "id": "Down",
    "level": 1,
    "parent": "Directions",
    "english": "Down",
    "bulgarian": "Долу",
    "image": "images/down.png",
    "audio": "audio/Долу.mp3",
    "hasChildren": false,
    "order": 57
  },
  {
    "id": "In",
    "level": 1,
    "parent": "Directions",
    "english": "In",
    "bulgarian": "В",
    "image": "images/in.png",
    "audio": "audio/В.mp3",
    "hasChildren": false,
    "order": 58
  },
  {
    "id": "Out",
    "level": 1,
    "parent": "Directions",
    "english": "Out",
    "bulgarian": "Извън",
    "image": "images/out.png",
    "audio": "audio/Извън.mp3",
    "hasChildren": false,
    "order": 59
  },
  {
    "id": "Go",
    "level": 1,
    "parent": "Directions",
    "english": "Go",
    "bulgarian": "Отиди",
    "image": "images/go.png",
    "audio": "audio/Отиди.mp3",
    "hasChildren": false,
    "order": 60
  },
  {
    "id": "Stop",
    "level": 1,
    "parent": "Directions",
    "english": "Stop",
    "bulgarian": "Спри",
    "image": "images/stop.png",
    "audio": "audio/Спри.mp3",
    "hasChildren": false,
    "order": 61
  },
  {
    "id": "Morning",
    "level": 1,
    "parent": "Directions",
    "english": "Morning",
    "bulgarian": "Сутрин",
    "image": "images/morning.png",
    "audio": "audio/Сутрин.mp3",
    "hasChildren": false,
    "order": 62
  },
  {
    "id": "Day",
    "level": 1,
    "parent": "Directions",
    "english": "Day",
    "bulgarian": "Ден",
    "image": "images/day.png",
    "audio": "audio/Ден.mp3",
    "hasChildren": false,
    "order": 63
  },
  {
    "id": "Night",
    "level": 1,
    "parent": "Directions",
    "english": "Night",
    "bulgarian": "Нощ",
    "image": "images/night.png",
    "audio": "audio/Нощ.mp3",
    "hasChildren": false,
    "order": 64
  },
  {
    "id": "Airplane",
    "level": 1,
    "parent": "Directions",
    "english": "Airplane",
    "bulgarian": "Самолет",
    "image": "images/airplane.png",
    "audio": "audio/Самолет.mp3",
    "hasChildren": false,
    "order": 65
  },
  {
    "id": "Car",
    "level": 1,
    "parent": "Directions",
    "english": "Car",
    "bulgarian": "Кола",
    "image": "images/Car.png",
    "audio": "audio/Кола.mp3",
    "hasChildren": false,
    "order": 66
  },
  {
    "id": "Phrases",
    "level": 0,
    "parent": null,
    "english": "Phrases",
    "bulgarian": "Фрази",
    "image": "images/phrases.png",
    "audio": "audio/Фрази.mp3",
    "hasChildren": true,
    "order": 67
  },
  {
    "id": "Hi",
    "level": 1,
    "parent": "Phrases",
    "english": "Hi",
    "bulgarian": "Здрасти",
    "image": "images/hi.png",
    "audio": "audio/Здрасти.mp3",
    "hasChildren": false,
    "order": 68
  },
  {
    "id": "Bye",
    "level": 1,
    "parent": "Phrases",
    "english": "Bye",
    "bulgarian": "Чао",
    "image": "images/bye.png",
    "audio": "audio/Чао.mp3",
    "hasChildren": false,
    "order": 69
  },
  {
    "id": "I Love You",
    "level": 1,
    "parent": "Phrases",
    "english": "I Love You",
    "bulgarian": "Обичам те",
    "image": "images/iloveyou.png",
    "audio": "audio/Обичам те.mp3",
    "hasChildren": false,
    "order": 70
  },
  {
    "id": "More",
    "level": 1,
    "parent": "Phrases",
    "english": "More",
    "bulgarian": "Още",
    "image": "imags/more.png",
    "audio": "imags/Още.mp3",
    "hasChildren": false,
    "order": 71
  },
  {
    "id": "Please",
    "level": 1,
    "parent": "Phrases",
    "english": "Please",
    "bulgarian": "Моля",
    "image": "images/please.png",
    "audio": "audio/Моля.mp3",
    "hasChildren": false,
    "order": 72
  },
  {
    "id": "Thank You",
    "level": 1,
    "parent": "Phrases",
    "english": "Thank You",
    "bulgarian": "Благодаря",
    "image": "images/thankyou.png",
    "audio": "audio/Благодаря.mp3",
    "hasChildren": false,
    "order": 73
  },
  {
    "id": "Goodnight",
    "level": 1,
    "parent": "Phrases",
    "english": "Goodnight",
    "bulgarian": "Лека нощ",
    "image": "images/goodnight.png",
    "audio": "audio/Лека нощ.mp3",
    "hasChildren": false,
    "order": 74
  },
  {
    "id": "Done",
    "level": 1,
    "parent": "Phrases",
    "english": "Done",
    "bulgarian": "Готово",
    "image": "images/done.png",
    "audio": "audio/Готово.mp3",
    "hasChildren": false,
    "order": 75
  },
  {
    "id": "Want",
    "level": 1,
    "parent": "Phrases",
    "english": "Wants",
    "bulgarian": "Иска",
    "image": "images/want.png",
    "audio": "audio/Иска.mp3",
    "hasChildren": false,
    "order": 76
  },
  {
    "id": "Gently",
    "level": 1,
    "parent": "Phrases",
    "english": "Gently",
    "bulgarian": "кротък",
    "image": "images/gently.png",
    "audio": "audio/кротък.mp3",
    "hasChildren": false,
    "order": 77
  },
  {
    "id": "Be Careful",
    "level": 1,
    "parent": "Phrases",
    "english": "Be Careful",
    "bulgarian": "бъди внимателен",
    "image": "images/Becareful.png",
    "audio": "audio/бъдивнимателен.mp3",
    "hasChildren": false,
    "order": 78
  },
  {
    "id": "Body",
    "level": 0,
    "parent": null,
    "english": "Body",
    "bulgarian": "Тяло",
    "image": "images/body.png",
    "audio": "audio/Тяло.mp3",
    "hasChildren": true,
    "order": 79
  },
  {
    "id": "Head",
    "level": 1,
    "parent": "Body",
    "english": "Head",
    "bulgarian": "Глава",
    "image": "images/head.png",
    "audio": "audio/Глава.mp3",
    "hasChildren": false,
    "order": 80
  },
  {
    "id": "Eyes",
    "level": 1,
    "parent": "Body",
    "english": "Eyes",
    "bulgarian": "Очи",
    "image": "images/eyes.png",
    "audio": "audio/Очи.mp3",
    "hasChildren": false,
    "order": 81
  },
  {
    "id": "Ears",
    "level": 1,
    "parent": "Body",
    "english": "Ears",
    "bulgarian": "Уши",
    "image": "images/ears.png",
    "audio": "audio/Уши.mp3",
    "hasChildren": false,
    "order": 82
  },
  {
    "id": "Nose",
    "level": 1,
    "parent": "Body",
    "english": "Nose",
    "bulgarian": "Нос",
    "image": "images/nose.png",
    "audio": "audio/Нос.mp3",
    "hasChildren": false,
    "order": 83
  },
  {
    "id": "Mouth",
    "level": 1,
    "parent": "Body",
    "english": "Mouth",
    "bulgarian": "Уста",
    "image": "images/mouth.png",
    "audio": "audio/Уста.mp3",
    "hasChildren": false,
    "order": 84
  },
  {
    "id": "Heart",
    "level": 1,
    "parent": "Body",
    "english": "Heart",
    "bulgarian": "Сърце",
    "image": "images/heart.png",
    "audio": "audio/Сърце.mp3",
    "hasChildren": false,
    "order": 85
  },
  {
    "id": "Arms",
    "level": 1,
    "parent": "Body",
    "english": "Arms",
    "bulgarian": "Ръце",
    "image": "images/arms.png",
    "audio": "audio/Ръце.mp3",
    "hasChildren": false,
    "order": 86
  },
  {
    "id": "Hands",
    "level": 1,
    "parent": "Body",
    "english": "Hands",
    "bulgarian": "Ръце",
    "image": "images/hands.png",
    "audio": "audio/Ръце.mp3",
    "hasChildren": false,
    "order": 87
  },
  {
    "id": "Legs",
    "level": 1,
    "parent": "Body",
    "english": "Legs",
    "bulgarian": "Крака",
    "image": "images/legs.png",
    "audio": "audio/Крака.mp3",
    "hasChildren": false,
    "order": 88
  },
  {
    "id": "Feet",
    "level": 1,
    "parent": "Body",
    "english": "Feet",
    "bulgarian": "Стъпала",
    "image": "images/feet.png",
    "audio": "audio/Стъпала.mp3",
    "hasChildren": false,
    "order": 89
  },
  {
    "id": "Stomach",
    "level": 1,
    "parent": "Body",
    "english": "Stomach",
    "bulgarian": "Стомах",
    "image": "images/stomach.png",
    "audio": "audio/Стомах.mp3",
    "hasChildren": false,
    "order": 90
  },
  {
    "id": "Clothes",
    "level": 0,
    "parent": null,
    "english": "Clothes",
    "bulgarian": "Дрехи",
    "image": "images/clothes.png",
    "audio": "audio/Дрехи.mp3",
    "hasChildren": true,
    "order": 91
  },
  {
    "id": "Dress",
    "level": 1,
    "parent": "Clothes",
    "english": "Dress",
    "bulgarian": "Рокля",
    "image": "images/dress.png",
    "audio": "audio/Рокля.mp3",
    "hasChildren": false,
    "order": 92
  },
  {
    "id": "Pants",
    "level": 1,
    "parent": "Clothes",
    "english": "Pants",
    "bulgarian": "Панталони",
    "image": "images/pants.png",
    "audio": "audio/Панталони.mp3",
    "hasChildren": false,
    "order": 93
  },
  {
    "id": "Shirt",
    "level": 1,
    "parent": "Clothes",
    "english": "Shirt",
    "bulgarian": "Риза",
    "image": "images/Shirt.png",
    "audio": "audio/Риза.mp3",
    "hasChildren": false,
    "order": 94
  },
  {
    "id": "Shoes",
    "level": 1,
    "parent": "Clothes",
    "english": "Shoes",
    "bulgarian": "Обувки",
    "image": "images/shoes.png",
    "audio": "audio/Обувки.mp3",
    "hasChildren": false,
    "order": 95
  },
  {
    "id": "Skirt",
    "level": 1,
    "parent": "Clothes",
    "english": "Skirt",
    "bulgarian": "Пола",
    "image": "images/skirt.png",
    "audio": "audio/Пола.mp3",
    "hasChildren": false,
    "order": 96
  },
  {
    "id": "Diaper",
    "level": 1,
    "parent": "Clothes",
    "english": "Diaper",
    "bulgarian": "Пелена",
    "image": "images/diaper.png",
    "audio": "audio/Пелена.mp3",
    "hasChildren": false,
    "order": 97
  },
  {
    "id": "Animals",
    "level": 0,
    "parent": null,
    "english": "Animals",
    "bulgarian": "Животни",
    "image": "images/animals.png",
    "audio": "audio/Животни.mp3",
    "hasChildren": true,
    "order": 98
  },
  {
    "id": "Horse",
    "level": 1,
    "parent": "Animals",
    "english": "Horse",
    "bulgarian": "Кон",
    "image": "images/horse.png",
    "audio": "audio/Кон.mp3",
    "hasChildren": false,
    "order": 99
  },
  {
    "id": "Alpaca",
    "level": 1,
    "parent": "Animals",
    "english": "Alpaca",
    "bulgarian": "Алпака",
    "image": "images/alpaca.png",
    "audio": "audio/Алпака.mp3",
    "hasChildren": false,
    "order": 100
  },
  {
    "id": "Cat",
    "level": 1,
    "parent": "Animals",
    "english": "Cat",
    "bulgarian": "Котка",
    "image": "images/Cat.png",
    "audio": "audio/Котка.mp3",
    "hasChildren": false,
    "order": 101
  },
  {
    "id": "Dog",
    "level": 1,
    "parent": "Animals",
    "english": "Dog",
    "bulgarian": "Куче",
    "image": "images/dog.png",
    "audio": "audio/Куче.mp3",
    "hasChildren": false,
    "order": 102
  },
  {
    "id": "Fish",
    "level": 1,
    "parent": "Animals",
    "english": "Fish",
    "bulgarian": "Риба",
    "image": "images/Fish.png",
    "audio": "audio/Риба.mp3",
    "hasChildren": false,
    "order": 103
  },
  {
    "id": "Places",
    "level": 0,
    "parent": null,
    "english": "Places",
    "bulgarian": "Места",
    "image": "images/places.png",
    "audio": "audio/Места.mp3",
    "hasChildren": true,
    "order": 104
  },
  {
    "id": "Mira's Room",
    "level": 1,
    "parent": "Places",
    "english": "Mira's Room",
    "bulgarian": "Стаята на Мира",
    "image": "images/mirasroom.png",
    "audio": "audio/Стаята на Мира.mp3",
    "hasChildren": false,
    "order": 105
  },
  {
    "id": "Home",
    "level": 1,
    "parent": "Places",
    "english": "Home",
    "bulgarian": "Дом",
    "image": "images/home.png",
    "audio": "audio/Дом.mp3",
    "hasChildren": false,
    "order": 106
  },
  {
    "id": "Bathroom",
    "level": 1,
    "parent": "Places",
    "english": "Bathroom",
    "bulgarian": "Баня",
    "image": "images/bathroom.png",
    "audio": "audio/Баня.mp3",
    "hasChildren": false,
    "order": 107
  },
  {
    "id": "Living Room",
    "level": 1,
    "parent": "Places",
    "english": "Living Room",
    "bulgarian": "Дневна",
    "image": "images/livingroom.png",
    "audio": "audio/Дневна.mp3",
    "hasChildren": false,
    "order": 108
  },
  {
    "id": "Kitchen",
    "level": 1,
    "parent": "Places",
    "english": "Kitchen",
    "bulgarian": "Кухня",
    "image": "images/kitchen.png",
    "audio": "audio/Кухня.mp3",
    "hasChildren": false,
    "order": 109
  },
  {
    "id": "Play",
    "level": 0,
    "parent": null,
    "english": "Play",
    "bulgarian": "Играй",
    "image": "images/play.png",
    "audio": "audio/Играй.mp3",
    "hasChildren": true,
    "order": 110
  },
  {
    "id": "Book",
    "level": 1,
    "parent": "Play",
    "english": "Book",
    "bulgarian": "Книга",
    "image": "images/book.png",
    "audio": "audio/Книга.mp3",
    "hasChildren": false,
    "order": 111
  },
  {
    "id": "Colors",
    "level": 1,
    "parent": "Play",
    "english": "Colors",
    "bulgarian": "Цветове",
    "image": "images/Colors.png",
    "audio": "audio/Цветове.mp3",
    "hasChildren": true,
    "order": 112
  },
  {
    "id": "Red",
    "level": 2,
    "parent": "Colors",
    "english": "Red",
    "bulgarian": "Червен",
    "image": "images/red.png",
    "audio": "audio/Червен.mp3",
    "hasChildren": false,
    "order": 113
  },
  {
    "id": "Orange",
    "level": 2,
    "parent": "Colors",
    "english": "Orange",
    "bulgarian": "Оранжев",
    "image": "images/orange.png",
    "audio": "audio/Оранжев.mp3",
    "hasChildren": false,
    "order": 114
  },
  {
    "id": "Yellow",
    "level": 2,
    "parent": "Colors",
    "english": "Yellow",
    "bulgarian": "Жълт",
    "image": "images/yellow.png",
    "audio": "audio/Жълт.mp3",
    "hasChildren": false,
    "order": 115
  },
  {
    "id": "Green",
    "level": 2,
    "parent": "Colors",
    "english": "Green",
    "bulgarian": "Зелен",
    "image": "images/green.png",
    "audio": "audio/Зелен.mp3",
    "hasChildren": false,
    "order": 116
  },
  {
    "id": "Blue",
    "level": 2,
    "parent": "Colors",
    "english": "Blue",
    "bulgarian": "Син",
    "image": "images/blue.png",
    "audio": "audio/Син.mp3",
    "hasChildren": false,
    "order": 117
  },
  {
    "id": "Purple",
    "level": 2,
    "parent": "Colors",
    "english": "Purple",
    "bulgarian": "Лилав",
    "image": "images/purple.png",
    "audio": "audio/Лилав.mp3",
    "hasChildren": false,
    "order": 118
  },
  {
    "id": "Draw",
    "level": 1,
    "parent": "Play",
    "english": "Draw",
    "bulgarian": "Рисувам",
    "image": "images/draw.png",
    "audio": "audio/Рисувам.mp3",
    "hasChildren": false,
    "order": 119
  },
  {
    "id": "Crayons",
    "level": 2,
    "parent": "Draw",
    "english": "Crayons",
    "bulgarian": "Пастели",
    "image": "images/crayons.png",
    "audio": "audio/Пастели.mp3",
    "hasChildren": false,
    "order": 120
  },
  {
    "id": "Markers",
    "level": 2,
    "parent": "Draw",
    "english": "Markers",
    "bulgarian": "Маркер",
    "image": "images/markers.png",
    "audio": "audio/Маркер.mp3",
    "hasChildren": false,
    "order": 121
  },
  {
    "id": "Paper",
    "level": 2,
    "parent": "Draw",
    "english": "Paper",
    "bulgarian": "Хартия",
    "image": "images/paper.png",
    "audio": "audio/Хартия.mp3",
    "hasChildren": false,
    "order": 122
  },
  {
    "id": "Games",
    "level": 1,
    "parent": "Play",
    "english": "Games",
    "bulgarian": "Игри",
    "image": "images/games.png",
    "audio": "audio/Игри.mp3",
    "hasChildren": false,
    "order": 123
  },
  {
    "id": "Phone",
    "level": 1,
    "parent": "Play",
    "english": "Phone",
    "bulgarian": "Телефон",
    "image": "images/phone.png",
    "audio": "audio/Телефон.mp3",
    "hasChildren": false,
    "order": 124
  },
  {
    "id": "Toys",
    "level": 1,
    "parent": "Play",
    "english": "Toys",
    "bulgarian": "Играчки",
    "image": "images/toys.png",
    "audio": "audio/Играчки.mp3",
    "hasChildren": true,
    "order": 125
  },
  {
    "id": "Ball",
    "level": 2,
    "parent": "Toys",
    "english": "Ball",
    "bulgarian": "Топка",
    "image": "images/ball.png",
    "audio": "audio/Топка.mp3",
    "hasChildren": false,
    "order": 126
  },
  {
    "id": "Doll",
    "level": 2,
    "parent": "Toys",
    "english": "Doll",
    "bulgarian": "Кукла",
    "image": "images/doll.png",
    "audio": "audio/Кукла.mp3",
    "hasChildren": false,
    "order": 127
  },
  {
    "id": "Truck",
    "level": 2,
    "parent": "Toys",
    "english": "Truck",
    "bulgarian": "Камион",
    "image": "images/truck.png",
    "audio": "audio/Камион.mp3",
    "hasChildren": false,
    "order": 128
  },
  {
    "id": "TV",
    "level": 1,
    "parent": "Play",
    "english": "TV",
    "bulgarian": "Телевизор",
    "image": "images/tv.png",
    "audio": "audio/Телевизор.mp3",
    "hasChildren": true,
    "order": 129
  },
  {
    "id": "Bluey",
    "level": 2,
    "parent": "TV",
    "english": "Bluey",
    "bulgarian": "Блуи",
    "image": "images/bluey.png",
    "audio": "audio/Блуи.mp3",
    "hasChildren": false,
    "order": 130
  },
  {
    "id": "Mickey Mouse",
    "level": 2,
    "parent": "TV",
    "english": "Mickey Mouse",
    "bulgarian": "Мики Маус",
    "image": "images/MickeyMouse.png",
    "audio": "audio/Мики Маус.mp3",
    "hasChildren": false,
    "order": 131
  },
  {
    "id": "Movie",
    "level": 2,
    "parent": "TV",
    "english": "Movie",
    "bulgarian": "Филм",
    "image": "images/movie.png",
    "audio": "audio/Филм.mp3",
    "hasChildren": false,
    "order": 132
  },
  {
    "id": "Star Wars",
    "level": 2,
    "parent": "TV",
    "english": "Star Wars",
    "bulgarian": "Междузвездни войни",
    "image": "images/starwars.png",
    "audio": "audio/Междузвездни войни.mp3",
    "hasChildren": false,
    "order": 133
  },
  {
    "id": "Questions",
    "level": 0,
    "parent": null,
    "english": "Questions",
    "bulgarian": "Въпроси",
    "image": "images/questions.png",
    "audio": "audio/Въпроси.mp3",
    "hasChildren": true,
    "order": 134
  },
  {
    "id": "What do you need?",
    "level": 1,
    "parent": "Questions",
    "english": "What do you need?",
    "bulgarian": "От какво имаш нужда?",
    "image": "images/whatdoyouneed.png",
    "audio": "audio/От какво имаш нужда?.mp3",
    "hasChildren": false,
    "order": 135
  },
  {
    "id": "What do you want?",
    "level": 1,
    "parent": "Questions",
    "english": "What do you want?",
    "bulgarian": "Какво искаш?",
    "image": "images/whatdoyouwant.png",
    "audio": "audio/Какво искаш?.mp3",
    "hasChildren": false,
    "order": 136
  },
  {
    "id": "Who?",
    "level": 1,
    "parent": "Questions",
    "english": "Who?",
    "bulgarian": "Кой?",
    "image": "images/who.png",
    "audio": "audio/Кой?.mp3",
    "hasChildren": true,
    "order": 137
  },
  {
    "id": "Me",
    "level": 2,
    "parent": "Who?",
    "english": "Me",
    "bulgarian": "Аз",
    "image": "images/me.png",
    "audio": "audio/Аз.mp3",
    "hasChildren": false,
    "order": 138
  },
  {
    "id": "You",
    "level": 2,
    "parent": "Who?",
    "english": "You",
    "bulgarian": "Ти",
    "image": "images/you.png",
    "audio": "audio/Ти.mp3",
    "hasChildren": false,
    "order": 139
  },
  {
    "id": "We",
    "level": 2,
    "parent": "Who?",
    "english": "We",
    "bulgarian": "Ние",
    "image": "images/we.png",
    "audio": "audio/Ние.mp3",
    "hasChildren": false,
    "order": 140
  },
  {
    "id": "Mom",
    "level": 2,
    "parent": "Family",
    "english": "Mom",
    "bulgarian": "Мама",
    "image": "images/Mom.png",
    "audio": "audio/Мама.mp3",
    "hasChildren": false,
    "order": 141
  },
  {
    "id": "Dad",
    "level": 2,
    "parent": "Family",
    "english": "Dad",
    "bulgarian": "Татко",
    "image": "images/dad.png",
    "audio": "audio/Татко.mp3",
    "hasChildren": false,
    "order": 142
  },
  {
    "id": "Grandma",
    "level": 2,
    "parent": "Family",
    "english": "Grandma",
    "bulgarian": "Баба",
    "image": "images/grandma.png",
    "audio": "audio/Баба.mp3",
    "hasChildren": false,
    "order": 143
  },
  {
    "id": "Grandpa",
    "level": 2,
    "parent": "Family",
    "english": "Grandpa",
    "bulgarian": "Дядо",
    "image": "images/grandpa.png",
    "audio": "audio/Дядо.mp3",
    "hasChildren": false,
    "order": 144
  },
  {
    "id": "Aunt Peyton",
    "level": 2,
    "parent": "Family",
    "english": "Aunt Peyton",
    "bulgarian": "Леля Пейтън",
    "image": "images/Auntpeyton.png",
    "audio": "audio/Леля Пейтън.mp3",
    "hasChildren": false,
    "order": 145
  },
  {
    "id": "Uncle Addie",
    "level": 2,
    "parent": "Family",
    "english": "Uncle Addie",
    "bulgarian": "Чичо Ади",
    "image": "images/uncleaddie.png",
    "audio": "audio/Чичо Ади.mp3",
    "hasChildren": false,
    "order": 146
  },
  {
    "id": "Uncle Jasce",
    "level": 2,
    "parent": "Family",
    "english": "Uncle Jasce",
    "bulgarian": "Чичо Джейс",
    "image": "images/unclejasce.png",
    "audio": "audio/Чичо Джейс.mp3",
    "hasChildren": false,
    "order": 147
  },
  {
    "id": "Cat",
    "level": 2,
    "parent": "Who?",
    "english": "Cat",
    "bulgarian": "Котка",
    "image": "images/Cat.png",
    "audio": "audio/Котка.mp3",
    "hasChildren": false,
    "order": 148
  },
  {
    "id": "Dog",
    "level": 2,
    "parent": "Who?",
    "english": "Dog",
    "bulgarian": "Куче",
    "image": "images/dog.png",
    "audio": "audio/Куче.mp3",
    "hasChildren": false,
    "order": 149
  },
  {
    "id": "Fish",
    "level": 2,
    "parent": "Who?",
    "english": "Fish",
    "bulgarian": "Риба",
    "image": "images/Fish.png",
    "audio": "audio/Риба.mp3",
    "hasChildren": false,
    "order": 150
  },
  {
    "id": "Neighbors",
    "level": 2,
    "parent": "Family",
    "english": "Neighbors",
    "bulgarian": "Съседи",
    "image": "images/neighbors.png",
    "audio": "audio/Съседи.mp3",
    "hasChildren": false,
    "order": 151
  },
  {
    "id": "Baby",
    "level": 2,
    "parent": "Family",
    "english": "Baby",
    "bulgarian": "Бебе",
    "image": "images/baby.png",
    "audio": "audio/Бебе.mp3",
    "hasChildren": false,
    "order": 152
  },
  {
    "id": "What?",
    "level": 1,
    "parent": "Questions",
    "english": "What?",
    "bulgarian": "Какво?",
    "image": "images/what.png",
    "audio": "audio/Какво?.mp3",
    "hasChildren": false,
    "order": 153
  },
  {
    "id": "When?",
    "level": 1,
    "parent": "Questions",
    "english": "When?",
    "bulgarian": "Кога?",
    "image": "images/when.png",
    "audio": "audio/Кога?.mp3",
    "hasChildren": true,
    "order": 154
  },
  {
    "id": "Morning",
    "level": 2,
    "parent": "When?",
    "english": "Morning",
    "bulgarian": "Сутрин",
    "image": "images/morning.png",
    "audio": "audio/Сутрин.mp3",
    "hasChildren": false,
    "order": 155
  },
  {
    "id": "Day",
    "level": 2,
    "parent": "When?",
    "english": "Day",
    "bulgarian": "Ден",
    "image": "images/day.png",
    "audio": "audio/Ден.mp3",
    "hasChildren": false,
    "order": 156
  },
  {
    "id": "Night",
    "level": 2,
    "parent": "When?",
    "english": "Night",
    "bulgarian": "Нощ",
    "image": "images/night.png",
    "audio": "audio/Нощ.mp3",
    "hasChildren": false,
    "order": 157
  },
  {
    "id": "Where?",
    "level": 1,
    "parent": "Questions",
    "english": "Where?",
    "bulgarian": "Къде?",
    "image": "images/where.png",
    "audio": "audio/Къде?.mp3",
    "hasChildren": true,
    "order": 158
  },
  {
    "id": "Home",
    "level": 2,
    "parent": "Where?",
    "english": "Home",
    "bulgarian": "Дом",
    "image": "images/home.png",
    "audio": "audio/Дом.mp3",
    "hasChildren": false,
    "order": 159
  },
  {
    "id": "Mira's Room",
    "level": 2,
    "parent": "Where?",
    "english": "Mira's Room",
    "bulgarian": "Стаята на Мира",
    "image": "images/mirasroom.png",
    "audio": "audio/Стаята на Мира.mp3",
    "hasChildren": false,
    "order": 160
  },
  {
    "id": "Bathroom",
    "level": 2,
    "parent": "Where?",
    "english": "Bathroom",
    "bulgarian": "Баня",
    "image": "images/bathroom.png",
    "audio": "audio/Баня.mp3",
    "hasChildren": false,
    "order": 161
  },
  {
    "id": "How?",
    "level": 1,
    "parent": "Questions",
    "english": "How?",
    "bulgarian": "Как?",
    "image": "images/how.png",
    "audio": "audio/Как?.mp3",
    "hasChildren": false,
    "order": 162
  },
  {
    "id": "Why?",
    "level": 1,
    "parent": "Questions",
    "english": "Why?",
    "bulgarian": "Защо?",
    "image": "images/why.png",
    "audio": "audio/Защо?.mp3",
    "hasChildren": false,
    "order": 163
  },
  {
    "id": "Weather",
    "level": 0,
    "parent": null,
    "english": "Weather",
    "bulgarian": "Времето",
    "image": "images/weather.png",
    "audio": "audio/Времето.mp3",
    "hasChildren": true,
    "order": 164
  },
  {
    "id": "Hot",
    "level": 1,
    "parent": "Weather",
    "english": "Hot",
    "bulgarian": "Горещо",
    "image": "images/hot.png",
    "audio": "audio/Горещо.mp3",
    "hasChildren": false,
    "order": 165
  },
  {
    "id": "Cold",
    "level": 1,
    "parent": "Weather",
    "english": "Cold",
    "bulgarian": "Студено",
    "image": "images/cold.png",
    "audio": "audio/Студено.mp3",
    "hasChildren": false,
    "order": 166
  },
  {
    "id": "Sun",
    "level": 1,
    "parent": "Weather",
    "english": "Sun",
    "bulgarian": "Слънце",
    "image": "images/sun.png",
    "audio": "audio/Слънце.mp3",
    "hasChildren": false,
    "order": 167
  },
  {
    "id": "Rain",
    "level": 1,
    "parent": "Weather",
    "english": "Rain",
    "bulgarian": "Дъжд",
    "image": "images/rain.png",
    "audio": "audio/Дъжд.mp3",
    "hasChildren": false,
    "order": 168
  },
  {
    "id": "Snow",
    "level": 1,
    "parent": "Weather",
    "english": "Snow",
    "bulgarian": "Сняг",
    "image": "images/snow.png",
    "audio": "audio/Сняг.mp3",
    "hasChildren": false,
    "order": 169
  },
  {
    "id": "Windy",
    "level": 1,
    "parent": "Weather",
    "english": "Windy",
    "bulgarian": "Ветровито",
    "image": "images/windy.png",
    "audio": "audio/Ветровито.mp3",
    "hasChildren": false,
    "order": 170
  }
];
