const vocabulary = [
   {
    id: "Yes",
    level: 0,
    parent: null,
    english: "Yes",
    bulgarian: "Да",
    image: "images/yes.png",
    audio: "audio/Да.mp3",
    hasChildren: false,
  },
  {
    id: "No",
    level: 0,
    parent: null,
    english: "No",
    bulgarian: "Не",
    image: "images/no.png",
    audio: "audio/Не.mp3",
    hasChildren: false,
  },
    {
    id: "Family",
    level: 0,
    parent: null,
    english: "Family",
    bulgarian: "Семейство",
    image: "images/family.png",
    audio: "audio/Семейство.mp3",
    hasChildren: true,
  },
   {
    id: "Mom",
    level: 1,
    parent: "Family",
    english: "Mom",
    bulgarian: "Мама",
    image: "images/Mom.png",
    audio: "audio/Мама.mp3",
    hasChildren: false,
  },
   {
    id: "Dad",
    level: 1,
    parent: "Family",
    english: "Dad",
    bulgarian: "Татко",
    image: "images/dad.png",
    audio: "audio/Татко.mp3",
    hasChildren: false,
  },
  {
    id: "Grandma",
    level: 1,
    parent: "Family",
    english: "Grandma",
    bulgarian: "Баба",
    image: "images/grandma.png",
    audio: "audio/Баба.mp3",
    hasChildren: false,
  },
  {
    id: "Grandpa",
    level: 1,
    parent: "Family",
    english: "Grandpa",
    bulgarian: "Дядо",
    image: "images/grandpa.png",
    audio: "audio/Дядо.mp3",
    hasChildren: false,
  },
  {
    id: "Home",
    level: 1,
    parent: "Family",
    english: "Home",
    bulgarian: "Дом",
    image: "images/home.png",
    audio: "audio/Дом.mp3",
    hasChildren: false,
  },
   {
    id: "Aunt Peyton",
    level: 1,
    parent: "Family",
    english: "Aunt Peyton",
    bulgarian: "Леля Пейтън",
    image: "images/Auntpeyton.png",
    audio: "audio/Леля Пейтън.mp3",
    hasChildren: false,
  },
   {
    id: "Uncle Addie",
    level: 1,
    parent: "Family",
    english: "Uncle Addie",
    bulgarian: "Чичо Ади",
    image: "images/uncleaddie.png",
    audio: "audio/Чичо Ади.mp3",
    hasChildren: false,
  },
  {
    id: "Uncle Jasce",
    level: 1,
    parent: "Family",
    english: "Uncle Jasce",
    bulgarian: "Чичо Джейс",
    image: "images/unclejasce.png",
    audio: "audio/Чичо Джейс.mp3",
    hasChildren: false,
  },
  {
    id: "Neighbors",
    level: 1,
    parent: "Family",
    english: "Neighbors",
    bulgarian: "Съседи",
    image: "images/neighbors.png",
    audio: "audio/Съседи.mp3",
    hasChildren: false,
  },
   {
    id: "Baby",
    level: 1,
    parent: "Family",
    english: "Baby",
    bulgarian: "Бебе",
    image: "images/baby.png",
    audio: "audio/Бебе.mp3",
    hasChildren: false,
  },
   {
    id: "Feelings",
    level: 0,
    parent: null,
    english: "Feelings",
    bulgarian: "Чувства",
    image: "images/feelings.png",
    audio: "audio/Чувства.mp3",
    hasChildren: true,
  },
   {
    id: "Needs",
    level: 0,
    parent: null,
    english: "Needs",
    bulgarian: "Нуждае се",
    image: "images/needs.png",
    audio: "audio/Нуждае.mp3",
    hasChildren: true,
  },
    {
    id: ,
    level: 0,
    parent: null,
    english: "Food",
    bulgarian: "Храна",
    image: "images/food.png",
    audio: "audio/Храна.mp3",
    hasChildren: true,
  },
   {
    id: "Clothes",
    level: 0,
    parent: null,
    english: "Clothes",
    bulgarian: "Дрехи",
    image: "images/clothes.png",
    audio: "audio/Дрехи.mp3",
    hasChildren: true,
  },
  {
    id: "Animals",
    level: 0,
    parent: null,
    english: "Animals",
    bulgarian: "Животни",
    image: "images/animals.png",
    audio: "audio/Животни.mp3",
    hasChildren: true,
  },
  {
    id: "Body",
    level: 0,
    parent: null,
    english: "Body",
    bulgarian: "Тяло",
    image: "images/body.png",
    audio: "audio/Тяло.mp3",
    hasChildren: true,
  },
  {
    id: "Directions",
    level: 0,
    parent: null,
    english: "Directions",
    bulgarian: "Указания",
    image: "images/directions.png",
    audio: "audio/Указания.mp3",
    hasChildren: true,
  },
  {
    id: "Help",
    level: 0,
    parent: null,
    english: "Help",
    bulgarian: "Помощ",
    image: "images/help.png",
    audio: "audio/Помощ.mp3",
    hasChildren: false,
  },
  {
    id: "Phrases",
    level: 0,
    parent: null,
    english: "Phrases",
    bulgarian: "Фрази",
    image: "images/phrases.png",
    audio: "audio/Фрази.mp3",
    hasChildren: true,
  },
  {
    id: "Places",
    level: 0,
    parent: null,
    english: "Places",
    bulgarian: "Места",
    image: "images/places.png",
    audio: "audio/Места.mp3",
    hasChildren: true,
  },
  {
    id: "Play",
    level: 0,
    parent: null,
    english: "Play",
    bulgarian: "Играй",
    image: "images/play.png",
    audio: "audio/Играй.mp3",
    hasChildren: true,
  },
  {
    id: "Questions",
    level: 0,
    parent: null,
    english: "Questions",
    bulgarian: "Въпроси",
    image: "images/questions.png",
    audio: "audio/Въпроси.mp3",
    hasChildren: true,
  },
  {
    id: "Stop",
    level: 0,
    parent: null,
    english: "Stop",
    bulgarian: "Спри",
    image: "images/stop.png",
    audio: "audio/Спри.mp3",
    hasChildren: false,
  },
  {
    id: "Wants",
    level: 0,
    parent: null,
    english: "Wants",
    bulgarian: "Иска",
    image: "images/want.png",
    audio: "audio/Иска.mp3",
    hasChildren: true,
  },
  {
    id: "Weather",
    level: 0,
    parent: null,
    english: "Weather",
    bulgarian: "Времето",
    image: "images/weather.png",
    audio: "audio/Времето.mp3",
    hasChildren: true,
  },
  {
    id: "Horse",
    level: 1,
    parent: "Animals",
    english: "Horse",
    bulgarian: "Кон",
    image: "images/horse.png",
    audio: "audio/Кон.mp3",
    hasChildren: false,
  },
  {
    id: "Alpaca",
    level: 1,
    parent: "Animals",
    english: "Alpaca",
    bulgarian: "Алпака",
    image: "images/alpaca.png",
    audio: "audio/Алпака.mp3",
    hasChildren: false,
  },
  {
    id: "Cat",
    level: 1,
    parent: "Animals",
    english: "Cat",
    bulgarian: "Котка",
    image: "images/Cat.png",
    audio: "audio/Котка.mp3",
    hasChildren: false,
  },
  {
    id: "Dog",
    level: 1,
    parent: "Animals",
    english: "Dog",
    bulgarian: "Куче",
    image: "images/dog.png",
    audio: "audio/Куче.mp3",
    hasChildren: false,
  },
  {
    id: "Fish",
    level: 1,
    parent: "Animals",
    english: "Fish",
    bulgarian: "Риба",
    image: "images/Fish.png",
    audio: "audio/Риба.mp3",
    hasChildren: false,
  },
  {
    id: "Arms",
    level: 1,
    parent: "Body",
    english: "Arms",
    bulgarian: "Ръце",
    image: "images/arms.png",
    audio: "audio/Ръце.mp3",
    hasChildren: false,
  },
  {
    id: "Ears",
    level: 1,
    parent: "Body",
    english: "Ears",
    bulgarian: "Уши",
    image: "images/ears.png",
    audio: "audio/Уши.mp3",
    hasChildren: false,
  },
  {
    id: "Eyes",
    level: 1,
    parent: "Body",
    english: "Eyes",
    bulgarian: "Очи",
    image: "images/eyes.png",
    audio: "audio/Очи.mp3",
    hasChildren: false,
  },
  {
    id: "Feet",
    level: 1,
    parent: "Body",
    english: "Feet",
    bulgarian: "Стъпала",
    image: "images/feet.png",
    audio: "audio/Стъпала.mp3",
    hasChildren: false,
  },
  {
    id: "Hands",
    level: 1,
    parent: "Body",
    english: "Hands",
    bulgarian: "Ръце",
    image: "images/hands.png",
    audio: "audio/Ръце.mp3",
    hasChildren: false,
  },
  {
    id: "Head",
    level: 1,
    parent: "Body",
    english: "Head",
    bulgarian: "Глава",
    image: "images/head.png",
    audio: "audio/Глава.mp3",
    hasChildren: false,
  },
  {
    id: "Heart",
    level: 1,
    parent: "Body",
    english: "Heart",
    bulgarian: "Сърце",
    image: "images/heart.png",
    audio: "audio/Сърце.mp3",
    hasChildren: false,
  },
  {
    id: "Legs",
    level: 1,
    parent: "Body",
    english: "Legs",
    bulgarian: "Крака",
    image: "images/legs.png",
    audio: "audio/Крака.mp3",
    hasChildren: false,
  },
  {
    id: "Mouth",
    level: 1,
    parent: "Body",
    english: "Mouth",
    bulgarian: "Уста",
    image: "images/mouth.png",
    audio: "audio/Уста.mp3",
    hasChildren: false,
  },
  {
    id: "Nose",
    level: 1,
    parent: "Body",
    english: "Nose",
    bulgarian: "Нос",
    image: "images/nose.png",
    audio: "audio/Нос.mp3",
    hasChildren: false,
  },
  {
    id: "Stomach",
    level: 1,
    parent: "Body",
    english: "Stomach",
    bulgarian: "Стомах",
    image: "images/stomach.png",
    audio: "audio/Стомах.mp3",
    hasChildren: false,
  },
  {
    id: "Bath",
    level: 2,
    parent: "Clean",
    english: "Bath",
    bulgarian: "Вана",
    image: "images/bath.png",
    audio: "audio/Вана.mp3",
    hasChildren: false,
  },
  {
    id: "Hands",
    level: 2,
    parent: "Clean",
    english: "Hands",
    bulgarian: "Ръце",
    image: "images/hands.png",
    audio: "audio/Ръце.mp3",
    hasChildren: false,
  },
  {
    id: "Teeth",
    level: 2,
    parent: "Clean",
    english: "Teeth",
    bulgarian: "Зъби",
    image: "images/teeth.png",
    audio: "audio/Зъби.mp3",
    hasChildren: false,
  },
  {
    id: "Diaper",
    level: 1,
    parent: "Clothes",
    english: "Diaper",
    bulgarian: "Пелена",
    image: "images/diaper.png",
    audio: "audio/Пелена.mp3",
    hasChildren: false,
  },
  {
    id: "Dress",
    level: 1,
    parent: "Clothes",
    english: "Dress",
    bulgarian: "Рокля",
    image: "images/dress.png",
    audio: "audio/Рокля.mp3",
    hasChildren: false,
  },
  {
    id: "Pants",
    level: 1,
    parent: "Clothes",
    english: "Pants",
    bulgarian: "Панталони",
    image: "images/pants.png",
    audio: "audio/Панталони.mp3",
    hasChildren: false,
  },
  {
    id: "Shirt",
    level: 1,
    parent: "Clothes",
    english: "Shirt",
    bulgarian: "Риза",
    image: "images/Shirt.png",
    audio: "audio/Риза.mp3",
    hasChildren: false,
  },
  {
    id: "Shoes",
    level: 1,
    parent: "Clothes",
    english: "Shoes",
    bulgarian: "Обувки",
    image: "images/shoes.png",
    audio: "audio/Обувки.mp3",
    hasChildren: false,
  },
  {
    id: "Skirt",
    level: 1,
    parent: "Clothes",
    english: "Skirt",
    bulgarian: "Пола",
    image: "images/skirt.png",
    audio: "audio/Пола.mp3",
    hasChildren: false,
  },
  {
    id: "Blue",
    level: 2,
    parent: "Colors",
    english: "Blue",
    bulgarian: "Син",
    image: "images/blue.png",
    audio: "audio/Син.mp3",
    hasChildren: false,
  },
  {
    id: "Green",
    level: 2,
    parent: "Colors",
    english: "Green",
    bulgarian: "Зелен",
    image: "images/green.png",
    audio: "audio/Зелен.mp3",
    hasChildren: false,
  },
  {
    id: "Orange",
    level: 2,
    parent: "Colors",
    english: "Orange",
    bulgarian: "Оранжев",
    image: "images/orange.png",
    audio: "audio/Оранжев.mp3",
    hasChildren: false,
  },
  {
    id: "Purple",
    level: 2,
    parent: "Colors",
    english: "Purple",
    bulgarian: "Лилав",
    image: "images/purple.png",
    audio: "audio/Лилав.mp3",
    hasChildren: false,
  },
  {
    id: "Red",
    level: 2,
    parent: "Colors",
    english: "Red",
    bulgarian: "Червен",
    image: "images/red.png",
    audio: "audio/Червен.mp3",
    hasChildren: false,
  },
  {
    id: "Yellow",
    level: 2,
    parent: "Colors",
    english: "Yellow",
    bulgarian: "Жълт",
    image: "images/yellow.png",
    audio: "audio/Жълт.mp3",
    hasChildren: false,
  },
  {
    id: "Airplane",
    level: 1,
    parent: "Directions",
    english: "Airplane",
    bulgarian: "Самолет",
    image: "images/airplane.png",
    audio: "audio/Самолет.mp3",
    hasChildren: false,
  },
  {
    id: "Car",
    level: 1,
    parent: "Directions",
    english: "Car",
    bulgarian: "Кола",
    image: "images/Car.png",
    audio: "audio/Кола.mp3",
    hasChildren: false,
  },
  {
    id: "Day",
    level: 1,
    parent: "Directions",
    english: "Day",
    bulgarian: "Ден",
    image: "images/day.png",
    audio: "audio/Ден.mp3",
    hasChildren: false,
  },
  {
    id: "Down",
    level: 1,
    parent: "Directions",
    english: "Down",
    bulgarian: "Долу",
    image: "images/down.png",
    audio: "audio/Долу.mp3",
    hasChildren: false,
  },
  {
    id: "Go",
    level: 1,
    parent: "Directions",
    english: "Go",
    bulgarian: "Отиди",
    image: "images/go.png",
    audio: "audio/Отиди.mp3",
    hasChildren: false,
  },
  {
    id: "In",
    level: 1,
    parent: "Directions",
    english: "In",
    bulgarian: "В",
    image: "images/in.png",
    audio: "audio/В.mp3",
    hasChildren: false,
  },
  {
    id: "Morning",
    level: 1,
    parent: "Directions",
    english: "Morning",
    bulgarian: "Сутрин",
    image: "images/morning.png",
    audio: "audio/Сутрин.mp3",
    hasChildren: false,
  },
  {
    id: "Night",
    level: 1,
    parent: "Directions",
    english: "Night",
    bulgarian: "Нощ",
    image: "images/night.png",
    audio: "audio/Нощ.mp3",
    hasChildren: false,
  },
  {
    id: "Out",
    level: 1,
    parent: "Directions",
    english: "Out",
    bulgarian: "Извън",
    image: "images/out.png",
    audio: "audio/Извън.mp3",
    hasChildren: false,
  },
  {
    id: "Stop",
    level: 1,
    parent: "Directions",
    english: "Stop",
    bulgarian: "Спри",
    image: "images/stop.png",
    audio: "audio/Спри.mp3",
    hasChildren: false,
  },
  {
    id: "Up",
    level: 1,
    parent: "Directions",
    english: "Up",
    bulgarian: "Горе",
    image: "images/up.png",
    audio: "audio/Горе.mp3",
    hasChildren: false,
  },
  {
    id: "Crayons",
    level: 2,
    parent: "Draw",
    english: "Crayons",
    bulgarian: "Пастели",
    image: "images/crayons.png",
    audio: "audio/Пастели.mp3",
    hasChildren: false,
  },
  {
    id: "Markers",
    level: 2,
    parent: "Draw",
    english: "Markers",
    bulgarian: "Маркер",
    image: "images/markers.png",
    audio: "audio/Маркер.mp3",
    hasChildren: false,
  },
  {
    id: "Paper",
    level: 2,
    parent: "Draw",
    english: "Paper",
    bulgarian: "Хартия",
    image: "images/paper.png",
    audio: "audio/Хартия.mp3",
    hasChildren: false,
  },
   {
    id: "Water",
    level: 2,
    parent: "Drinks",
    english: "Water",
    bulgarian: "вода",
    image: "images/water.png",
    audio: "audio/вода.mp3",
    hasChildren: false,
  },
  {
    id: "Chocolate Milk",
    level: 2,
    parent: "Drinks",
    english: "Chocolate Milk",
    bulgarian: "Шоколадово мляко",
    image: "images/chocolatemilk.png",
    audio: "audio/Шоколадово мляко.mp3",
    hasChildren: false,
  },
  {
    id: "Juice",
    level: 2,
    parent: "Drinks",
    english: "Juice",
    bulgarian: "Сок",
    image: "images/juice.png",
    audio: "audio/Сок.mp3",
    hasChildren: false,
  },
  {
    id: "Milk",
    level: 2,
    parent: "Drinks",
    english: "Milk",
    bulgarian: "Мляко",
    image: "images/milk.png",
    audio: "audio/Мляко.mp3",
    hasChildren: false,
  },

 {
    id: "Happy",
    level: 1,
    parent: "Feelings",
    english: "Happy",
    bulgarian: "Щастлив",
    image: "images/happy.png",
    audio: "audio/Щастлив.mp3",
    hasChildren: false,
  },
  {
    id: "Sad",
    level: 1,
    parent: "Feelings",
    english: "Sad",
    bulgarian: "Тъжен",
    image: "images/sad.png",
    audio: "audio/Тъжен.mp3",
    hasChildren: false,
  },
   {
    id: "Angry",
    level: 1,
    parent: "Feelings",
    english: "Angry",
    bulgarian: "Ядосан",
    image: "images/angry.png",
    audio: "audio/Ядосан.mp3",
    hasChildren: false,
  },
   {
    id: "Tired",
    level: 1,
    parent: "Feelings",
    english: "Tired",
    bulgarian: "Уморен",
    image: "images/tired.png",
    audio: "audio/Уморен.mp3",
    hasChildren: false,
  },
   {
    id: "Scared",
    level: 1,
    parent: "Feelings",
    english: "Scared",
    bulgarian: "Уплашен",
    image: "images/scared.png",
    audio: "audio/Уплашен.mp3",
    hasChildren: false,
  },
  {
    id: "Silly",
    level: 1,
    parent: "Feelings",
    english: "Silly",
    bulgarian: "Глупав",
    image: "images/silly.png",
    audio: "audio/Глупав.mp3",
    hasChildren: false,
  },
   {
    id: "Confused",
    level: 1,
    parent: "Feelings",
    english: "Confused",
    bulgarian: "Объркан",
    image: "images/confused.png",
    audio: "audio/Объркан.mp3",
    hasChildren: false,
  },
  {
    id: "Disgust",
    level: 1,
    parent: "Feelings",
    english: "Disgust",
    bulgarian: "Отвращение",
    image: "images/disgust.png",
    audio: "audio/Отвращение.mp3",
    hasChildren: false,
  },
  {
    id: "Cereal",
    level: 1,
    parent: "Food",
    english: "Cereal",
    bulgarian: "Зърнена закуска",
    image: "images/cereal.png",
    audio: "audio/Зърнена закуска.mp3",
    hasChildren: false,
  },
  {
    id: "Fruit",
    level: 1,
    parent: "Food",
    english: "Fruit",
    bulgarian: "Плод",
    image: "images/fruit.png",
    audio: "audio/Плод.mp3",
    hasChildren: false,
  },
  {
    id: "Pizza",
    level: 1,
    parent: "Food",
    english: "Pizza",
    bulgarian: "Пица",
    image: "images/pizza.png",
    audio: "audio/Пица.mp3",
    hasChildren: false,
  },
  {
    id: "Apple",
    level: 2,
    parent: "Fruit",
    english: "Apple",
    bulgarian: "Ябълка",
    image: "images/apple.png",
    audio: "audio/Ябълка.mp3",
    hasChildren: false,
  },
  {
    id: "Banana",
    level: 2,
    parent: "Fruit",
    english: "Banana",
    bulgarian: "Банан",
    image: "images/banana.png",
    audio: "audio/Банан.mp3",
    hasChildren: false,
  },
  {
    id: "Orange",
    level: 2,
    parent: "Fruit",
    english: "Orange",
    bulgarian: "Портокал",
    image: "images/orange.png",
    audio: "audio/Портокал.mp3",
    hasChildren: false,
  },
  {
    id: "Strawberry",
    level: 2,
    parent: "Fruit",
    english: "Strawberry",
    bulgarian: "Ягода",
    image: "images/Strawberry.png",
    audio: "audio/Ягода.mp3",
    hasChildren: false,
  },
  {
    id: "Watermelon",
    level: 2,
    parent: "Fruit",
    english: "Watermelon",
    bulgarian: "Диня",
    image: "images/watermelon.png",
    audio: "audio/Диня.mp3",
    hasChildren: false,
  },
  {
    id: "Bathroom",
    level: 1,
    parent: "Needs",
    english: "Bathroom",
    bulgarian: "Баня",
    image: "images/bathroom.png",
    audio: "audio/Баня.mp3",
    hasChildren: false,
  },
  {
    id: "Bed",
    level: 1,
    parent: "Needs",
    english: "Bed",
    bulgarian: "Легло",
    image: "images/Bed.png",
    audio: "audio/Легло.mp3",
    hasChildren: false,
  },
  {
    id: "Clean",
    level: 1,
    parent: "Needs",
    english: "Clean",
    bulgarian: "Чист",
    image: "images/clean.png",
    audio: "audio/Чист.mp3",
    hasChildren: true,
  },
  {
    id: "Dirty",
    level: 1,
    parent: "Needs",
    english: "Dirty",
    bulgarian: "Мръсен",
    image: "images/dirty.png",
    audio: "audio/Мръсен.mp3",
    hasChildren: false,
  },
  {
    id: "Drinks",
    level: 1,
    parent: "Needs",
    english: "Drinks",
    bulgarian: "Напитки",
    image: "images/drinks.png",
    audio: "audio/Напитки.mp3",
    hasChildren: true,
  },
   {
    id: "Drinks",
    level: 2,
    parent: "thirsty",
    english: "Drinks",
    bulgarian: "Напитки",
    image: "images/drinks.png",
    audio: "audio/Напитки.mp3",
    hasChildren: true,
  },
  {
    id: "Food",
    level: 1,
    parent: "Needs",
    english: "Food",
    bulgarian: "Храна",
    image: "images/food.png",
    audio: "audio/Храна.mp3",
    hasChildren: true,
  },
  {
    id: "Hungry",
    level: 1,
    parent: "Needs",
    english: "Hungry",
    bulgarian: "Гладен",
    image: "images/hungry.png",
    audio: "audio/Гладен.mp3",
    hasChildren: false,
  },
  {
    id: "Hurts",
    level: 1,
    parent: "Needs",
    english: "Hurts",
    bulgarian: "Боли",
    image: "images/hurts.png",
    audio: "audio/Боли.mp3",
    hasChildren: false,
  },
  {
    id: "Pee",
    level: 1,
    parent: "Needs",
    english: "Pee",
    bulgarian: "Пиш",
    image: "images/pee.png",
    audio: "audio/Пиш.mp3",
    hasChildren: false,
  },
  {
    id: "Poop",
    level: 1,
    parent: "Needs",
    english: "Poop",
    bulgarian: "Ака",
    image: "images/poop.png",
    audio: "audio/Ака.mp3",
    hasChildren: false,
  },
   {
    id: "Pee",
    level: 2,
    parent: "bathroom",
    english: "Pee",
    bulgarian: "Пиш",
    image: "images/pee.png",
    audio: "audio/Пиш.mp3",
    hasChildren: false,
  },
  {
    id: "Poop",
    level: 2,
    parent: "bathroom",
    english: "Poop",
    bulgarian: "Ака",
    image: "images/poop.png",
    audio: "audio/Ака.mp3",
    hasChildren: false,
  },
  {
    id: "Sick",
    level: 1,
    parent: "Needs",
    english: "Sick",
    bulgarian: "Болен",
    image: "images/sick.png",
    audio: "audio/Болен.mp3",
    hasChildren: false,
  },
  {
    id: "Sleepy",
    level: 1,
    parent: "Needs",
    english: "Sleepy",
    bulgarian: "Сънлив",
    image: "images/sleepy.png",
    audio: "audio/Сънлив.mp3",
    hasChildren: false,
  },
  {
    id: "Thirsty",
    level: 1,
    parent: "Needs",
    english: "Thirsty",
    bulgarian: "Жаден",
    image: "images/thirsty.png",
    audio: "audio/Жаден.mp3",
    hasChildren: true,
  },
  {
    id: "Bye",
    level: 1,
    parent: "Phrases",
    english: "Bye",
    bulgarian: "Чао",
    image: "images/bye.png",
    audio: "audio/Чао.mp3",
    hasChildren: false,
  },
  {
    id: "Done",
    level: 1,
    parent: "Phrases",
    english: "Done",
    bulgarian: "Готово",
    image: "images/done.png",
    audio: "audio/Готово.mp3",
    hasChildren: false,
  },
  {
    id: "Goodnight",
    level: 1,
    parent: "Phrases",
    english: "Goodnight",
    bulgarian: "Лека нощ",
    image: "images/goodnight.png",
    audio: "audio/Лека нощ.mp3",
    hasChildren: false,
  },
  {
    id: "Hi",
    level: 1,
    parent: "Phrases",
    english: "Hi",
    bulgarian: "Здрасти",
    image: "images/hi.png",
    audio: "audio/Здрасти.mp3",
    hasChildren: false,
  },
  {
    id: "I Love You",
    level: 1,
    parent: "Phrases",
    english: "I Love You",
    bulgarian: "Обичам те",
    image: "images/iloveyou.png",
    audio: "audio/Обичам те.mp3",
    hasChildren: false,
  },
  {
    id: "More",
    level: 1,
    parent: "Phrases",
    english: "More",
    bulgarian: "Още",
    image: "imags/more.png",
    audio: "imags/Още.mp3",
    hasChildren: false,
  },
  {
    id: "Play",
    level: 1,
    parent: "Phrases",
    english: "Play",
    bulgarian: "Играй",
    image: "images/play.png",
    audio: "audio/Играй.mp3",
    hasChildren: false,
  },
  {
    id: "Please",
    level: 1,
    parent: "Phrases",
    english: "Please",
    bulgarian: "Моля",
    image: "images/please.png",
    audio: "audio/Моля.mp3",
    hasChildren: false,
  },
  {
    id: "Thank You",
    level: 1,
    parent: "Phrases",
    english: "Thank You",
    bulgarian: "Благодаря",
    image: "images/thankyou.png",
    audio: "audio/Благодаря.mp3",
    hasChildren: false,
  },
  {
    id: "Bathroom",
    level: 1,
    parent: "Places",
    english: "Bathroom",
    bulgarian: "Баня",
    image: "images/bathroom.png",
    audio: "audio/Баня.mp3",
    hasChildren: true,
  },
  {
    id: "Home",
    level: 1,
    parent: "Places",
    english: "Home",
    bulgarian: "Дом",
    image: "images/home.png",
    audio: "audio/Дом.mp3",
    hasChildren: false,
  },
  {
    id: "Kitchen",
    level: 1,
    parent: "Places",
    english: "Kitchen",
    bulgarian: "Кухня",
    image: "images/kitchen.png",
    audio: "audio/Кухня.mp3",
    hasChildren: false,
  },
  {
    id: "Living Room",
    level: 1,
    parent: "Places",
    english: "Living Room",
    bulgarian: "Дневна",
    image: "images/livingroom.png",
    audio: "audio/Дневна.mp3",
    hasChildren: false,
  },
  {
    id: "Mira's Room",
    level: 1,
    parent: "Places",
    english: "Mira's Room",
    bulgarian: "Стаята на Мира",
    image: "images/mirasroom.png",
    audio: "audio/Стаята на Мира.mp3",
    hasChildren: false,
  },
  {
    id: "Colors",
    level: 1,
    parent: "Play",
    english: "Colors",
    bulgarian: "Цветове",
    image: "images/Colors.png",
    audio: "audio/Цветове.mp3",
    hasChildren: false,
  },
  {
    id: "Draw",
    level: 1,
    parent: "Play",
    english: "Draw",
    bulgarian: "Рисувам",
    image: "images/draw.png",
    audio: "audio/Рисувам.mp3",
    hasChildren: false,
  },
  {
    id: "Games",
    level: 1,
    parent: "Play",
    english: "Games",
    bulgarian: "Игри",
    image: "images/games.png",
    audio: "audio/Игри.mp3",
    hasChildren: false,
  },
  {
    id: "Phone",
    level: 1,
    parent: "Play",
    english: "Phone",
    bulgarian: "Телефон",
    image: "images/phone.png",
    audio: "audio/Телефон.mp3",
    hasChildren: false,
  },
  {
    id: "Toys",
    level: 1,
    parent: "Play",
    english: "Toys",
    bulgarian: "Играчки",
    image: "images/toys.png",
    audio: "audio/Играчки.mp3",
    hasChildren: true,
  },
  {
    id: "TV",
    level: 1,
    parent: "Play",
    english: "TV",
    bulgarian: "Телевизор",
    image: "images/tv.png",
    audio: "audio/Телевизор.mp3",
    hasChildren: true,
  },
  {
    id: "How?",
    level: 1,
    parent: "Questions",
    english: "How?",
    bulgarian: "Как?",
    image: "images/how.png",
    audio: "audio/Как?.mp3",
    hasChildren: false,
  },
  {
    id: "What do you need?",
    level: 1,
    parent: "Questions",
    english: "What do you need?",
    bulgarian: "От какво имаш нужда?",
    image: "images/whatdoyouneed.png",
    audio: "audio/От какво имаш нужда?.mp3",
    hasChildren: false,
  },
  {
    id: "What do you want?",
    level: 1,
    parent: "Questions",
    english: "What do you want?",
    bulgarian: "Какво искаш?",
    image: "images/whatdoyouwant.png",
    audio: "audio/Какво искаш?.mp3",
    hasChildren: false,
  },
  {
    id: "What?",
    level: 1,
    parent: "Questions",
    english: "What?",
    bulgarian: "Какво?",
    image: "images/what.png",
    audio: "audio/Какво?.mp3",
    hasChildren: false,
  },
  {
    id: "When?",
    level: 1,
    parent: "Questions",
    english: "When?",
    bulgarian: "Кога?",
    image: "images/when.png",
    audio: "audio/Кога?.mp3",
    hasChildren: true,
  },
  {
    id: "Where?",
    level: 1,
    parent: "Questions",
    english: "Where?",
    bulgarian: "Къде?",
    image: "images/where.png",
    audio: "audio/Къде?.mp3",
    hasChildren: true,
  },
  {
    id: "Who?",
    level: 1,
    parent: "Questions",
    english: "Who?",
    bulgarian: "Кой?",
    image: "images/who.png",
    audio: "audio/Кой?.mp3",
    hasChildren: true,
  },
  {
    id: "Why?",
    level: 1,
    parent: "Questions",
    english: "Why?",
    bulgarian: "Защо?",
    image: "images/why.png",
    audio: "audio/Защо?.mp3",
    hasChildren: false,
  },
  {
    id: "Ball",
    level: 2,
    parent: "Toys",
    english: "Ball",
    bulgarian: "Топка",
    image: "images/ball.png",
    audio: "audio/Топка.mp3",
    hasChildren: false,
  },
  {
    id: "Doll",
    level: 2,
    parent: "Toys",
    english: "Doll",
    bulgarian: "Кукла",
    image: "images/doll.png",
    audio: "audio/Кукла.mp3",
    hasChildren: false,
  },
  {
    id: "Truck",
    level: 2,
    parent: "Toys",
    english: "Truck",
    bulgarian: "Камион",
    image: "images/truck.png",
    audio: "audio/Камион.mp3",
    hasChildren: false,
  },
  {
    id: "Bluey",
    level: 1,
    parent: "TV",
    english: "Bluey",
    bulgarian: "Блуи",
    image: "images/bluey.png",
    audio: "audio/Блуи.mp3",
    hasChildren: false,
  },
  {
    id: "Mickey Mouse",
    level: 1,
    parent: "TV",
    english: "Mickey Mouse",
    bulgarian: "Мики Маус",
    image: "images/MickeyMouse.png",
    audio: "audio/Мики Маус.mp3",
    hasChildren: false,
  },
  {
    id: "Movie",
    level: 1,
    parent: "TV",
    english: "Movie",
    bulgarian: "Филм",
    image: "images/movie.png",
    audio: "audio/Филм.mp3",
    hasChildren: false,
  },
  {
    id: "Star Wars",
    level: 1,
    parent: "TV",
    english: "Star Wars",
    bulgarian: "Междузвездни войни",
    image: "images/starwars.png",
    audio: "audio/Междузвездни войни.mp3",
    hasChildren: false,
  },
  {
    id: "Book",
    level: 1,
    parent: "Wants",
    english: "Book",
    bulgarian: "Книга",
    image: "images/book.png",
    audio: "audio/Книга.mp3",
    hasChildren: false,
  },
  {
    id: "Cold",
    level: 1,
    parent: "Weather",
    english: "Cold",
    bulgarian: "Студено",
    image: "images/cold.png",
    audio: "audio/Студено.mp3",
    hasChildren: false,
  },
  {
    id: "Hot",
    level: 1,
    parent: "Weather",
    english: "Hot",
    bulgarian: "Горещо",
    image: "images/hot.png",
    audio: "audio/Горещо.mp3",
    hasChildren: false,
  },
  {
    id: "Rain",
    level: 1,
    parent: "Weather",
    english: "Rain",
    bulgarian: "Дъжд",
    image: "images/rain.png",
    audio: "audio/Дъжд.mp3",
    hasChildren: false,
  },
  {
    id: "Snow",
    level: 1,
    parent: "Weather",
    english: "Snow",
    bulgarian: "Сняг",
    image: "images/snow.png",
    audio: "audio/Сняг.mp3",
    hasChildren: false,
  },
  {
    id: "Sun",
    level: 1,
    parent: "Weather",
    english: "Sun",
    bulgarian: "Слънце",
    image: "images/sun.png",
    audio: "audio/Слънце.mp3",
    hasChildren: false,
  },
  {
    id: "Windy",
    level: 1,
    parent: "Weather",
    english: "Windy",
    bulgarian: "Ветровито",
    image: "images/windy.png",
    audio: "audio/Ветровито.mp3",
    hasChildren: false,
  },
  {
    id: "Day",
    level: 2,
    parent: "When?",
    english: "Day",
    bulgarian: "Ден",
    image: "images/day.png",
    audio: "audio/Ден.mp3",
    hasChildren: false,
  },
  {
    id: "Morning",
    level: 2,
    parent: "When?",
    english: "Morning",
    bulgarian: "Сутрин",
    image: "images/morning.png",
    audio: "audio/Сутрин.mp3",
    hasChildren: false,
  },
  {
    id: "Night",
    level: 2,
    parent: "When?",
    english: "Night",
    bulgarian: "Нощ",
    image: "images/night.png",
    audio: "audio/Нощ.mp3",
    hasChildren: false,
  },
  {
    id: "Home",
    level: 2,
    parent: "Where?",
    english: "Home",
    bulgarian: "Дом",
    image: "images/home.png",
    audio: "audio/Дом.mp3",
    hasChildren: false,
  },
  {
    id: "Mira's Room",
    level: 2,
    parent: "Where?",
    english: "Mira's Room",
    bulgarian: "Стаята на Мира",
    image: "images/mirasroom.png",
    audio: "audio/Стаята на Мира.mp3",
    hasChildren: false,
  },
  {
    id: "Aunt Peyton",
    level: 2,
    parent: "Who?",
    english: "Aunt Peyton",
    bulgarian: "Леля Пейтън",
    image: "images/Auntpeyton.png",
    audio: "audio/Леля Пейтън.mp3",
    hasChildren: false,
  },
  {
    id: "Baby",
    level: 2,
    parent: "Who?",
    english: "Baby",
    bulgarian: "Бебе",
    image: "images/baby.png",
    audio: "audio/Бебе.mp3",
    hasChildren: false,
  },
  {
    id: "Cat",
    level: 2,
    parent: "Who?",
    english: "Cat",
    bulgarian: "Котка",
    image: "images/Cat.png",
    audio: "audio/Котка.mp3",
    hasChildren: false,
  },
  {
    id: "Dad",
    level: 2,
    parent: "Who?",
    english: "Dad",
    bulgarian: "Татко",
    image: "images/dad.png",
    audio: "audio/Татко.mp3",
    hasChildren: false,
  },
  {
    id: "Dog",
    level: 2,
    parent: "Who?",
    english: "Dog",
    bulgarian: "Куче",
    image: "images/dog.png",
    audio: "audio/Куче.mp3",
    hasChildren: false,
  },
  {
    id: "Fish",
    level: 2,
    parent: "Who?",
    english: "Fish",
    bulgarian: "Риба",
    image: "images/Fish.png",
    audio: "audio/Риба.mp3",
    hasChildren: false,
  },
  {
    id: "Grandma",
    level: 2,
    parent: "Who?",
    english: "Grandma",
    bulgarian: "Баба",
    image: "images/grandma.png",
    audio: "audio/Баба.mp3",
    hasChildren: false,
  },
  {
    id: "Grandpa",
    level: 2,
    parent: "Who?",
    english: "Grandpa",
    bulgarian: "Дядо",
    image: "images/grandpa.png",
    audio: "audio/Дядо.mp3",
    hasChildren: false,
  },
  {
    id: "Me",
    level: 1,
    parent: "Who?",
    english: "Me",
    bulgarian: "Аз",
    image: "images/me.png",
    audio: "audio/Аз.mp3",
    hasChildren: false,
  },
  {
    id: "Mom",
    level: 2,
    parent: "Who?",
    english: "Mom",
    bulgarian: "Мама",
    image: "images/Mom.png",
    audio: "audio/Мама.mp3",
    hasChildren: false,
  },
  {
    id: "Neighbors",
    level: 2,
    parent: "Who?",
    english: "Neighbors",
    bulgarian: "Съседи",
    image: "images/neighbors.png",
    audio: "audio/Съседи.mp3",
    hasChildren: false,
  },
  {
    id: "Uncle Addie",
    level: 2,
    parent: "Who?",
    english: "Uncle Addie",
    bulgarian: "Чичо Ади",
    image: "images/uncleaddie.png",
    audio: "audio/Чичо Ади.mp3",
    hasChildren: false,
  },
  {
    id: "Uncle Jasce",
    level: 2,
    parent: "Who?",
    english: "Uncle Jasce",
    bulgarian: "Чичо Джейс",
    image: "images/unclejasce.png",
    audio: "audio/Чичо Джейс.mp3",
    hasChildren: false,
  },
  {
    id: "We",
    level: 1,
    parent: "Who?",
    english: "We",
    bulgarian: "Ние",
    image: "images/we.png",
    audio: "audio/Ние.mp3",
    hasChildren: false,
  },
  {
    id: "You",
    level: 1,
    parent: "Who?",
    english: "You",
    bulgarian: "Ти",
    image: "images/you.png",
    audio: "audio/Ти.mp3",
    hasChildren: false,
  },
];
