const vocabulary = [
  {
    id: "Horse",
    level: 1,
    parent: "Animals",
    english: "Horse",
    bulgarian: "Кон",
    image: "images/horse.png",
    audio: "audio/horse.mp3",
    hasChildren: false,
  },
  {
    id: "Alpaca",
    level: 1,
    parent: "Animals",
    english: "Alpaca",
    bulgarian: "Алпака",
    image: "images/alpaca.png",
    audio: "audio/alpaca.mp3",
    hasChildren: false,
  },
  {
    id: "Cat",
    level: 1,
    parent: "Animals",
    english: "Cat",
    bulgarian: "Котка",
    image: "images/Cat.png",
    audio: "audio/Cat.mp3",
    hasChildren: false,
  },
  {
    id: "Dog",
    level: 1,
    parent: "Animals",
    english: "Dog",
    bulgarian: "Куче",
    image: "images/dog.png",
    audio: "audio/dog.mp3",
    hasChildren: false,
  },
  {
    id: "Fish",
    level: 1,
    parent: "Animals",
    english: "Fish",
    bulgarian: "Риба",
    image: "images/Fish.png",
    audio: "audio/Fish.mp3",
    hasChildren: false,
  },
  {
    id: "Arms",
    level: 1,
    parent: "Body",
    english: "Arms",
    bulgarian: "Ръце",
    image: "images/arms.png",
    audio: "audio/arms.mp3",
    hasChildren: false,
  },
  {
    id: "Ears",
    level: 1,
    parent: "Body",
    english: "Ears",
    bulgarian: "Уши",
    image: "images/ears.png",
    audio: "audio/ears.mp3",
    hasChildren: false,
  },
  {
    id: "Eyes",
    level: 1,
    parent: "Body",
    english: "Eyes",
    bulgarian: "Очи",
    image: "images/eyes.png",
    audio: "audio/eyes.mp3",
    hasChildren: false,
  },
  {
    id: "Feet",
    level: 1,
    parent: "Body",
    english: "Feet",
    bulgarian: "Стъпала",
    image: "images/feet.png",
    audio: "audio/feet.mp3",
    hasChildren: false,
  },
  {
    id: "Hands",
    level: 1,
    parent: "Body",
    english: "Hands",
    bulgarian: "Ръце",
    image: "images/hands.png",
    audio: "audio/hands.mp3",
    hasChildren: false,
  },
  {
    id: "Head",
    level: 1,
    parent: "Body",
    english: "Head",
    bulgarian: "Глава",
    image: "images/head.png",
    audio: "audio/head.mp3",
    hasChildren: false,
  },
  {
    id: "Heart",
    level: 1,
    parent: "Body",
    english: "Heart",
    bulgarian: "Сърце",
    image: "images/heart.png",
    audio: "audio/heart.mp3",
    hasChildren: false,
  },
  {
    id: "Legs",
    level: 1,
    parent: "Body",
    english: "Legs",
    bulgarian: "Крака",
    image: "images/legs.png",
    audio: "audio/legs.mp3",
    hasChildren: false,
  },
  {
    id: "Mouth",
    level: 1,
    parent: "Body",
    english: "Mouth",
    bulgarian: "Уста",
    image: "images/mouth.png",
    audio: "audio/mouth.mp3",
    hasChildren: false,
  },
  {
    id: "Nose",
    level: 1,
    parent: "Body",
    english: "Nose",
    bulgarian: "Нос",
    image: "images/nose.png",
    audio: "audio/nose.mp3",
    hasChildren: false,
  },
  {
    id: "Stomach",
    level: 1,
    parent: "Body",
    english: "Stomach",
    bulgarian: "Стомах",
    image: "images/stomach.png",
    audio: "audio/stomach.mp3",
    hasChildren: false,
  },
  {
    id: "Bath",
    level: 2,
    parent: "Clean",
    english: "Bath",
    bulgarian: "Вана",
    image: "images/bath.png",
    audio: "audio/bath.mp3",
    hasChildren: false,
  },
  {
    id: "Hands",
    level: 2,
    parent: "Clean",
    english: "Hands",
    bulgarian: "Ръце",
    image: "images/hands.png",
    audio: "audio/hands.mp3",
    hasChildren: false,
  },
  {
    id: "Teeth",
    level: 2,
    parent: "Clean",
    english: "Teeth",
    bulgarian: "Зъби",
    image: "images/teeth.png",
    audio: "audio/teeth.mp3",
    hasChildren: false,
  },
  {
    id: "Diaper",
    level: 1,
    parent: "Clothes",
    english: "Diaper",
    bulgarian: "Пелена",
    image: "images/diaper.png",
    audio: "audio/diaper.mp3",
    hasChildren: false,
  },
  {
    id: "Dress",
    level: 1,
    parent: "Clothes",
    english: "Dress",
    bulgarian: "Рокля",
    image: "images/dress.png",
    audio: "audio/dress.mp3",
    hasChildren: false,
  },
  {
    id: "Pants",
    level: 1,
    parent: "Clothes",
    english: "Pants",
    bulgarian: "Панталони",
    image: "images/pants.png",
    audio: "audio/pants.mp3",
    hasChildren: false,
  },
  {
    id: "Shirt",
    level: 1,
    parent: "Clothes",
    english: "Shirt",
    bulgarian: "Риза",
    image: "images/Shirt.png",
    audio: "audio/Shirt.mp3",
    hasChildren: false,
  },
  {
    id: "Shoes",
    level: 1,
    parent: "Clothes",
    english: "Shoes",
    bulgarian: "Обувки",
    image: "images/shoes.png",
    audio: "audio/shoes.mp3",
    hasChildren: false,
  },
  {
    id: "Skirt",
    level: 1,
    parent: "Clothes",
    english: "Skirt",
    bulgarian: "Пола",
    image: "images/skirt.png",
    audio: "audio/skirt.mp3",
    hasChildren: false,
  },
  {
    id: "Blue",
    level: 2,
    parent: "Colors",
    english: "Blue",
    bulgarian: "Син",
    image: "images/blue.png",
    audio: "audio/blue.mp3",
    hasChildren: false,
  },
  {
    id: "Green",
    level: 2,
    parent: "Colors",
    english: "Green",
    bulgarian: "Зелен",
    image: "images/green.png",
    audio: "audio/green.mp3",
    hasChildren: false,
  },
  {
    id: "Orange",
    level: 2,
    parent: "Colors",
    english: "Orange",
    bulgarian: "Оранжев",
    image: "images/orange.png",
    audio: "audio/orange.mp3",
    hasChildren: false,
  },
  {
    id: "Purple",
    level: 2,
    parent: "Colors",
    english: "Purple",
    bulgarian: "Лилав",
    image: "images/purple.png",
    audio: "audio/purple.mp3",
    hasChildren: false,
  },
  {
    id: "Red",
    level: 2,
    parent: "Colors",
    english: "Red",
    bulgarian: "Червен",
    image: "images/red.png",
    audio: "audio/red.mp3",
    hasChildren: false,
  },
  {
    id: "Yellow",
    level: 2,
    parent: "Colors",
    english: "Yellow",
    bulgarian: "Жълт",
    image: "images/yellow.png",
    audio: "audio/yellow.mp3",
    hasChildren: false,
  },
  {
    id: "Airplane",
    level: 1,
    parent: "Directions",
    english: "Airplane",
    bulgarian: "Самолет",
    image: "images/airplane.png",
    audio: "audio/airplane.mp3",
    hasChildren: false,
  },
  {
    id: "Car",
    level: 1,
    parent: "Directions",
    english: "Car",
    bulgarian: "Кола",
    image: "images/Car.png",
    audio: "audio/Car.mp3",
    hasChildren: false,
  },
  {
    id: "Day",
    level: 1,
    parent: "Directions",
    english: "Day",
    bulgarian: "Ден",
    image: "images/day.png",
    audio: "audio/day.mp3",
    hasChildren: false,
  },
  {
    id: "Down",
    level: 1,
    parent: "Directions",
    english: "Down",
    bulgarian: "Долу",
    image: "images/down.png",
    audio: "audio/down.mp3",
    hasChildren: false,
  },
  {
    id: "Go",
    level: 1,
    parent: "Directions",
    english: "Go",
    bulgarian: "Отиди",
    image: "images/go.png",
    audio: "audio/go.mp3",
    hasChildren: false,
  },
  {
    id: "In",
    level: 1,
    parent: "Directions",
    english: "In",
    bulgarian: "В",
    image: "images/in.png",
    audio: "audio/in.mp3",
    hasChildren: false,
  },
  {
    id: "Morning",
    level: 1,
    parent: "Directions",
    english: "Morning",
    bulgarian: "Сутрин",
    image: "images/morning.png",
    audio: "audio/morning.mp3",
    hasChildren: false,
  },
  {
    id: "Night",
    level: 1,
    parent: "Directions",
    english: "Night",
    bulgarian: "Нощ",
    image: "images/night.png",
    audio: "audio/night.mp3",
    hasChildren: false,
  },
  {
    id: "Out",
    level: 1,
    parent: "Directions",
    english: "Out",
    bulgarian: "Извън",
    image: "images/out.png",
    audio: "audio/out.mp3",
    hasChildren: false,
  },
  {
    id: "Stop",
    level: 1,
    parent: "Directions",
    english: "Stop",
    bulgarian: "Спри",
    image: "images/stop.png",
    audio: "audio/stop.mp3",
    hasChildren: false,
  },
  {
    id: "Up",
    level: 1,
    parent: "Directions",
    english: "Up",
    bulgarian: "Горе",
    image: "images/up.png",
    audio: "audio/up.mp3",
    hasChildren: false,
  },
  {
    id: "Crayons",
    level: 2,
    parent: "Draw",
    english: "Crayons",
    bulgarian: "Пастели",
    image: "images/crayons.png",
    audio: "audio/crayons.mp3",
    hasChildren: false,
  },
  {
    id: "Markers",
    level: 2,
    parent: "Draw",
    english: "Markers",
    bulgarian: "Маркер",
    image: "images/markers.png",
    audio: "audio/markers.mp3",
    hasChildren: false,
  },
  {
    id: "Paper",
    level: 2,
    parent: "Draw",
    english: "Paper",
    bulgarian: "Хартия",
    image: "images/paper.png",
    audio: "audio/paper.mp3",
    hasChildren: false,
  },
  {
    id: "Chocolate Milk",
    level: 1,
    parent: "Drink",
    english: "Chocolate Milk",
    bulgarian: "Шоколадово мляко",
    image: "images/chocolatemilk.png",
    audio: "audio/chocolatemilk.mp3",
    hasChildren: false,
  },
  {
    id: "Juice",
    level: 1,
    parent: "Drink",
    english: "Juice",
    bulgarian: "Сок",
    image: "images/juice.png",
    audio: "audio/juice.mp3",
    hasChildren: false,
  },
  {
    id: "Milk",
    level: 1,
    parent: "Drink",
    english: "Milk",
    bulgarian: "Мляко",
    image: "images/milk.png",
    audio: "audio/milk.mp3",
    hasChildren: false,
  },
  {
    id: "Watermelon",
    level: 1,
    parent: "Drink",
    english: "Watermelon",
    bulgarian: "Диня",
    image: "images/water.png",
    audio: "audio/water.mp3",
    hasChildren: false,
  },
  {
    id: "Aunt Peyton",
    level: 1,
    parent: "Family",
    english: "Aunt Peyton",
    bulgarian: "Леля Пейтън",
    image: "images/Auntpeyton.png",
    audio: "audio/Auntpeyton.mp3",
    hasChildren: false,
  },
  {
    id: "Baby",
    level: 1,
    parent: "Family",
    english: "Baby",
    bulgarian: "Бебе",
    image: "images/baby.png",
    audio: "audio/baby.mp3",
    hasChildren: false,
  },
  {
    id: "Dad",
    level: 1,
    parent: "Family",
    english: "Dad",
    bulgarian: "Татко",
    image: "images/dad.png",
    audio: "audio/dad.mp3",
    hasChildren: false,
  },
  {
    id: "Grandma",
    level: 1,
    parent: "Family",
    english: "Grandma",
    bulgarian: "Баба",
    image: "images/grandma.png",
    audio: "audio/grandma.mp3",
    hasChildren: false,
  },
  {
    id: "Grandpa",
    level: 1,
    parent: "Family",
    english: "Grandpa",
    bulgarian: "Дядо",
    image: "images/grandpa.png",
    audio: "audio/grandpa.mp3",
    hasChildren: false,
  },
  {
    id: "Home",
    level: 1,
    parent: "Family",
    english: "Home",
    bulgarian: "Дом",
    image: "images/home.png",
    audio: "audio/home.mp3",
    hasChildren: false,
  },
  {
    id: "Mom",
    level: 1,
    parent: "Family",
    english: "Mom",
    bulgarian: "Мама",
    image: "images/Mom.png",
    audio: "audio/Mom.mp3",
    hasChildren: false,
  },
  {
    id: "Neighbors",
    level: 1,
    parent: "Family",
    english: "Neighbors",
    bulgarian: "Съседи",
    image: "images/neighbors.png",
    audio: "audio/neighbors.mp3",
    hasChildren: false,
  },
  {
    id: "Uncle Addie",
    level: 1,
    parent: "Family",
    english: "Uncle Addie",
    bulgarian: "Чичо Ади",
    image: "images/uncleaddie.png",
    audio: "audio/uncleaddie.mp3",
    hasChildren: false,
  },
  {
    id: "Uncle Jasce",
    level: 1,
    parent: "Family",
    english: "Uncle Jasce",
    bulgarian: "Чичо Джейс",
    image: "images/unclejasce.png",
    audio: "audio/unclejasce.mp3",
    hasChildren: false,
  },
  {
    id: "Angry",
    level: 1,
    parent: "Feelings",
    english: "Angry",
    bulgarian: "Ядосан",
    image: "images/angry.png",
    audio: "audio/angry.mp3",
    hasChildren: false,
  },
  {
    id: "Confused",
    level: 1,
    parent: "Feelings",
    english: "Confused",
    bulgarian: "Объркан",
    image: "images/confused/png",
    audio: "audio/confused/mp3",
    hasChildren: false,
  },
  {
    id: "Disgust",
    level: 1,
    parent: "Feelings",
    english: "Disgust",
    bulgarian: "Отвращение",
    image: "images/disgust.png",
    audio: "audio/disgust.mp3",
    hasChildren: false,
  },
  {
    id: "Happy",
    level: 1,
    parent: "Feelings",
    english: "Happy",
    bulgarian: "Щастлив",
    image: "images/happy.png",
    audio: "audio/happy.mp3",
    hasChildren: false,
  },
  {
    id: "Sad",
    level: 1,
    parent: "Feelings",
    english: "Sad",
    bulgarian: "Тъжен",
    image: "images/sad.png",
    audio: "audio/sad.mp3",
    hasChildren: false,
  },
  {
    id: "Scared",
    level: 1,
    parent: "Feelings",
    english: "Scared",
    bulgarian: "Уплашен",
    image: "images/scared.png",
    audio: "audio/scared.mp3",
    hasChildren: false,
  },
  {
    id: "Silly",
    level: 1,
    parent: "Feelings",
    english: "Silly",
    bulgarian: "Глупав",
    image: "images/silly.png",
    audio: "audio/silly.mp3",
    hasChildren: false,
  },
  {
    id: "Tired",
    level: 1,
    parent: "Feelings",
    english: "Tired",
    bulgarian: "Уморен",
    image: "images/tired.png",
    audio: "audio/tired.mp3",
    hasChildren: false,
  },
  {
    id: "Cereal",
    level: 1,
    parent: "Food",
    english: "Cereal",
    bulgarian: "Зърнена закуска",
    image: "images/cereal.png",
    audio: "audio/cereal.mp3",
    hasChildren: false,
  },
  {
    id: "Fruit",
    level: 1,
    parent: "Food",
    english: "Fruit",
    bulgarian: "Плод",
    image: "images/fruit.png",
    audio: "audio/fruit.mp3",
    hasChildren: false,
  },
  {
    id: "Pizza",
    level: 1,
    parent: "Food",
    english: "Pizza",
    bulgarian: "Пица",
    image: "images/pizza.png",
    audio: "audio/pizza.mp3",
    hasChildren: false,
  },
  {
    id: "Apple",
    level: 2,
    parent: "Fruit",
    english: "Apple",
    bulgarian: "Ябълка",
    image: "images/apple.png",
    audio: "audio/apple.mp3",
    hasChildren: false,
  },
  {
    id: "Banana",
    level: 2,
    parent: "Fruit",
    english: "Banana",
    bulgarian: "Банан",
    image: "images/banana.png",
    audio: "audio/banana.mp3",
    hasChildren: false,
  },
  {
    id: "Orange",
    level: 2,
    parent: "Fruit",
    english: "Orange",
    bulgarian: "Портокал",
    image: "images/orange.png",
    audio: "audio/orange.mp3",
    hasChildren: false,
  },
  {
    id: "Strawberry",
    level: 2,
    parent: "Fruit",
    english: "Strawberry",
    bulgarian: "Ягода",
    image: "images/Strawberry.png",
    audio: "audio/Strawberry.mp3",
    hasChildren: false,
  },
  {
    id: "Watermelon",
    level: 2,
    parent: "Fruit",
    english: "Watermelon",
    bulgarian: "Диня",
    image: "images/watermelon.png",
    audio: "audio/watermelon.mp3",
    hasChildren: false,
  },
  {
    id: "Bathroom",
    level: 1,
    parent: "Needs",
    english: "Bathroom",
    bulgarian: "Баня",
    image: "images/bathroom.png",
    audio: "audio/bathroom.mp3",
    hasChildren: true,
  },
  {
    id: "Bed",
    level: 1,
    parent: "Needs",
    english: "Bed",
    bulgarian: "Легло",
    image: "images/Bed.png",
    audio: "audio/Bed.mp3",
    hasChildren: false,
  },
  {
    id: "Clean",
    level: 1,
    parent: "Needs",
    english: "Clean",
    bulgarian: "Чист",
    image: "images/clean.png",
    audio: "audio/clean.mp3",
    hasChildren: true,
  },
  {
    id: "Dirty",
    level: 1,
    parent: "Needs",
    english: "Dirty",
    bulgarian: "Мръсен",
    image: "images/dirty.png",
    audio: "audio/dirty.mp3",
    hasChildren: false,
  },
  {
    id: "Drinks",
    level: 1,
    parent: "Needs",
    english: "Drinks",
    bulgarian: "Напитки",
    image: "images/drinks.png",
    audio: "audio/drinks.mp3",
    hasChildren: false,
  },
  {
    id: "Food",
    level: 1,
    parent: "Needs",
    english: "Food",
    bulgarian: "Храна",
    image: "images/food.png",
    audio: "audio/food.mp3",
    hasChildren: false,
  },
  {
    id: "Hungry",
    level: 1,
    parent: "Needs",
    english: "Hungry",
    bulgarian: "Гладен",
    image: "images/hungry.png",
    audio: "audio/hungry.mp3",
    hasChildren: true,
  },
  {
    id: "Hurts",
    level: 1,
    parent: "Needs",
    english: "Hurts",
    bulgarian: "Боли",
    image: "images/hurts.png",
    audio: "audio/hurts.mp3",
    hasChildren: false,
  },
  {
    id: "Pee",
    level: 1,
    parent: "Needs",
    english: "Pee",
    bulgarian: "Пиш",
    image: "images/pee.png",
    audio: "audio/pee.mp3",
    hasChildren: false,
  },
  {
    id: "Poop",
    level: 1,
    parent: "Needs",
    english: "Poop",
    bulgarian: "Ака",
    image: "images/poop.png",
    audio: "audio/poop.mp3",
    hasChildren: false,
  },
  {
    id: "Sick",
    level: 1,
    parent: "Needs",
    english: "Sick",
    bulgarian: "Болен",
    image: "images/sick.png",
    audio: "audio/sick.mp3",
    hasChildren: false,
  },
  {
    id: "Sleepy",
    level: 1,
    parent: "Needs",
    english: "Sleepy",
    bulgarian: "Сънлив",
    image: "images/sleepy.png",
    audio: "audio/sleepy.mp3",
    hasChildren: false,
  },
  {
    id: "Thirsty",
    level: 1,
    parent: "Needs",
    english: "Thirsty",
    bulgarian: "Жаден",
    image: "images/thirsty.png",
    audio: "audio/thirsty.mp3",
    hasChildren: true,
  },
  {
    id: "Animals",
    level: 0,
    parent: null,
    english: "Animals",
    bulgarian: "Животни",
    image: "images/animals.png",
    audio: "audio/animals.mp3",
    hasChildren: true,
  },
  {
    id: "Body",
    level: 0,
    parent: null,
    english: "Body",
    bulgarian: "Тяло",
    image: "images/body.png",
    audio: "audio/body.mp3",
    hasChildren: true,
  },
  {
    id: "Clothes",
    level: 0,
    parent: null,
    english: "Clothes",
    bulgarian: "Дрехи",
    image: "images/clothes.png",
    audio: "audio/clothes.mp3",
    hasChildren: true,
  },
  {
    id: "Directions",
    level: 0,
    parent: null,
    english: "Directions",
    bulgarian: "Указания",
    image: "images/directions.png",
    audio: "audio/directions.mp3",
    hasChildren: true,
  },
  {
    id: "Family",
    level: 0,
    parent: null,
    english: "Family",
    bulgarian: "Семейство",
    image: "images/family.png",
    audio: "audio/family.mp3",
    hasChildren: true,
  },
  {
    id: "Feelings",
    level: 0,
    parent: null,
    english: "Feelings",
    bulgarian: "Чувства",
    image: "images/feelings.png",
    audio: "audio/feelings.mp3",
    hasChildren: true,
  },
  {
    id: "Help",
    level: 0,
    parent: null,
    english: "Help",
    bulgarian: "Помощ",
    image: "images/help.png",
    audio: "audio/help.mp3",
    hasChildren: true,
  },
  {
    id: "Needs",
    level: 0,
    parent: null,
    english: "Needs",
    bulgarian: "Нуждае се",
    image: "images/needs.png",
    audio: "audio/needs.mp3",
    hasChildren: true,
  },
  {
    id: "No",
    level: 0,
    parent: null,
    english: "No",
    bulgarian: "Не",
    image: "images/no.png",
    audio: "audio/no.mp3",
    hasChildren: true,
  },
  {
    id: "Phrases",
    level: 0,
    parent: null,
    english: "Phrases",
    bulgarian: "Фрази",
    image: "images/phrases.png",
    audio: "audio/phrases.mp3",
    hasChildren: true,
  },
  {
    id: "Places",
    level: 0,
    parent: null,
    english: "Places",
    bulgarian: "Места",
    image: "images/places.png",
    audio: "audio/places.mp3",
    hasChildren: true,
  },
  {
    id: "Play",
    level: 0,
    parent: null,
    english: "Play",
    bulgarian: "Играй",
    image: "images/play.png",
    audio: "audio/play.mp3",
    hasChildren: true,
  },
  {
    id: "Questions",
    level: 0,
    parent: null,
    english: "Questions",
    bulgarian: "Въпроси",
    image: "images/questions.png",
    audio: "audio/questions.mp3",
    hasChildren: true,
  },
  {
    id: "Stop",
    level: 0,
    parent: null,
    english: "Stop",
    bulgarian: "Спри",
    image: "images/stop.png",
    audio: "audio/stop.mp3",
    hasChildren: true,
  },
  {
    id: "Wants",
    level: 0,
    parent: null,
    english: "Wants",
    bulgarian: "Иска",
    image: "images/want.png",
    audio: "audio/want.mp3",
    hasChildren: true,
  },
  {
    id: "Weather",
    level: 0,
    parent: null,
    english: "Weather",
    bulgarian: "Времето",
    image: "images/weather.png",
    audio: "audio/weather.mp3",
    hasChildren: true,
  },
  {
    id: "Yes",
    level: 0,
    parent: null,
    english: "Yes",
    bulgarian: "Да",
    image: "images/yes.png",
    audio: "audio/yes.mp3",
    hasChildren: true,
  },
  {
    id: "Bye",
    level: 1,
    parent: "Phrases",
    english: "Bye",
    bulgarian: "Чао",
    image: "images/bye.png",
    audio: "audio/bye.mp3",
    hasChildren: false,
  },
  {
    id: "Done",
    level: 1,
    parent: "Phrases",
    english: "Done",
    bulgarian: "Готово",
    image: "images/done.png",
    audio: "audio/done.mp3",
    hasChildren: false,
  },
  {
    id: "Goodnight",
    level: 1,
    parent: "Phrases",
    english: "Goodnight",
    bulgarian: "Лека нощ",
    image: "images/goodnight.png",
    audio: "audio/goodnight.mp3",
    hasChildren: false,
  },
  {
    id: "Hi",
    level: 1,
    parent: "Phrases",
    english: "Hi",
    bulgarian: "Здрасти",
    image: "images/hi.png",
    audio: "audio/hi.mp3",
    hasChildren: false,
  },
  {
    id: "I Love You",
    level: 1,
    parent: "Phrases",
    english: "I Love You",
    bulgarian: "Обичам те",
    image: "images/iloveyou.png",
    audio: "audio/iloveyou.mp3",
    hasChildren: false,
  },
  {
    id: "More",
    level: 1,
    parent: "Phrases",
    english: "More",
    bulgarian: "Още",
    image: "imags/more.png",
    audio: "imags/more.mp3",
    hasChildren: false,
  },
  {
    id: "Play",
    level: 1,
    parent: "Phrases",
    english: "Play",
    bulgarian: "Играй",
    image: "images/play.png",
    audio: "audio/play.mp3",
    hasChildren: false,
  },
  {
    id: "Please",
    level: 1,
    parent: "Phrases",
    english: "Please",
    bulgarian: "Моля",
    image: "images/please.png",
    audio: "audio/please.mp3",
    hasChildren: false,
  },
  {
    id: "Thank You",
    level: 1,
    parent: "Phrases",
    english: "Thank You",
    bulgarian: "Благодаря",
    image: "images/thankyou.png",
    audio: "audio/thankyou.mp3",
    hasChildren: false,
  },
  {
    id: "Bathroom",
    level: 1,
    parent: "Places",
    english: "Bathroom",
    bulgarian: "Баня",
    image: "images/bathroom.png",
    audio: "audio/bathroom.mp3",
    hasChildren: false,
  },
  {
    id: "Home",
    level: 1,
    parent: "Places",
    english: "Home",
    bulgarian: "Дом",
    image: "images/home.png",
    audio: "audio/home.mp3",
    hasChildren: false,
  },
  {
    id: "Kitchen",
    level: 1,
    parent: "Places",
    english: "Kitchen",
    bulgarian: "Кухня",
    image: "images/kitchen.png",
    audio: "audio/kitchen.mp3",
    hasChildren: false,
  },
  {
    id: "Living Room",
    level: 1,
    parent: "Places",
    english: "Living Room",
    bulgarian: "Дневна",
    image: "images/livingroom.png",
    audio: "audio/livingroom.mp3",
    hasChildren: false,
  },
  {
    id: "Mira's Room",
    level: 1,
    parent: "Places",
    english: "Mira's Room",
    bulgarian: "Стаята на Мира",
    image: "images/mirasroom.png",
    audio: "audio/mirasroom.mp3",
    hasChildren: false,
  },
  {
    id: "Colors",
    level: 1,
    parent: "Play",
    english: "Colors",
    bulgarian: "Цветове",
    image: "images/Colors.png",
    audio: "audio/Colors.mp3",
    hasChildren: false,
  },
  {
    id: "Draw",
    level: 1,
    parent: "Play",
    english: "Draw",
    bulgarian: "Рисувам",
    image: "images/draw.png",
    audio: "audio/draw.mp3",
    hasChildren: false,
  },
  {
    id: "Games",
    level: 1,
    parent: "Play",
    english: "Games",
    bulgarian: "Игри",
    image: "images/games.png",
    audio: "audio/games.mp3",
    hasChildren: false,
  },
  {
    id: "Phone",
    level: 1,
    parent: "Play",
    english: "Phone",
    bulgarian: "Телефон",
    image: "images/phone.png",
    audio: "audio/phone.mp3",
    hasChildren: false,
  },
  {
    id: "Toys",
    level: 1,
    parent: "Play",
    english: "Toys",
    bulgarian: "Играчки",
    image: "images/toys.png",
    audio: "audio/Играчки.mp3",
    hasChildren: true,
  },
  {
    id: "TV",
    level: 1,
    parent: "Play",
    english: "TV",
    bulgarian: "Телевизор",
    image: "images/tv.png",
    audio: "audio/tv.mp3",
    hasChildren: true,
  },
  {
    id: "How?",
    level: 1,
    parent: "Questions",
    english: "How?",
    bulgarian: "Как?",
    image: "images/how.png",
    audio: "audio/how.mp3",
    hasChildren: true,
  },
  {
    id: "What do you need?",
    level: 1,
    parent: "Questions",
    english: "What do you need?",
    bulgarian: "От какво имаш нужда?",
    image: "images/whatdoyouneed.png",
    audio: "audio/whatdoyouneed.mp3",
    hasChildren: false,
  },
  {
    id: "What do you want?",
    level: 1,
    parent: "Questions",
    english: "What do you want?",
    bulgarian: "Какво искаш?",
    image: "images/whatdoyouwant.png",
    audio: "audio/whatdoyouwant.mp3",
    hasChildren: false,
  },
  {
    id: "What?",
    level: 1,
    parent: "Questions",
    english: "What?",
    bulgarian: "Какво?",
    image: "images/what.png",
    audio: "audio/what.mp3",
    hasChildren: true,
  },
  {
    id: "When?",
    level: 1,
    parent: "Questions",
    english: "When?",
    bulgarian: "Кога?",
    image: "images/when.png",
    audio: "audio/when.mp3",
    hasChildren: true,
  },
  {
    id: "Where?",
    level: 1,
    parent: "Questions",
    english: "Where?",
    bulgarian: "Къде?",
    image: "images/where.png",
    audio: "audio/where.mp3",
    hasChildren: true,
  },
  {
    id: "Who?",
    level: 1,
    parent: "Questions",
    english: "Who?",
    bulgarian: "Кой?",
    image: "images/who.png",
    audio: "audio/who.mp3",
    hasChildren: true,
  },
  {
    id: "Why?",
    level: 1,
    parent: "Questions",
    english: "Why?",
    bulgarian: "Защо?",
    image: "images/why.png",
    audio: "audio/why.mp3",
    hasChildren: true,
  },
  {
    id: "Ball",
    level: 2,
    parent: "Toys",
    english: "Ball",
    bulgarian: "Топка",
    image: "images/ball.png",
    audio: "audio/ball.mp3",
    hasChildren: false,
  },
  {
    id: "Doll",
    level: 2,
    parent: "Toys",
    english: "Doll",
    bulgarian: "Кукла",
    image: "images/doll.png",
    audio: "audio/Кукла.mp3",
    hasChildren: false,
  },
  {
    id: "Truck",
    level: 2,
    parent: "Toys",
    english: "Truck",
    bulgarian: "Камион",
    image: "images/truck.png",
    audio: "audio/Камион.mp3",
    hasChildren: false,
  },
  {
    id: "Bluey",
    level: 1,
    parent: "TV",
    english: "Bluey",
    bulgarian: "Блуи",
    image: "images/bluey.png",
    audio: "audio/bluey.mp3",
    hasChildren: false,
  },
  {
    id: "Mickey Mouse",
    level: 1,
    parent: "TV",
    english: "Mickey Mouse",
    bulgarian: "Мики Маус",
    image: "images/MickeyMouse.png",
    audio: "audio/MickeyMouse.mp3",
    hasChildren: false,
  },
  {
    id: "Movie",
    level: 1,
    parent: "TV",
    english: "Movie",
    bulgarian: "Филм",
    image: "images/movie.png",
    audio: "audio/movie.mp3",
    hasChildren: false,
  },
  {
    id: "Star Wars",
    level: 1,
    parent: "TV",
    english: "Star Wars",
    bulgarian: "Междузвездни войни",
    image: "images/starwars.png",
    audio: "audio/starwars.mp3",
    hasChildren: false,
  },
  {
    id: "Book",
    level: 1,
    parent: "Wants",
    english: "Book",
    bulgarian: "Книга",
    image: "images/book.png",
    audio: "audio/book.mp3",
    hasChildren: false,
  },
  {
    id: "Cold",
    level: 1,
    parent: "Weather",
    english: "Cold",
    bulgarian: "Студено",
    image: "images/cold.png",
    audio: "audio/cold.mp3",
    hasChildren: false,
  },
  {
    id: "Hot",
    level: 1,
    parent: "Weather",
    english: "Hot",
    bulgarian: "Горещо",
    image: "images/hot.png",
    audio: "audio/hot.mp3",
    hasChildren: false,
  },
  {
    id: "Rain",
    level: 1,
    parent: "Weather",
    english: "Rain",
    bulgarian: "Дъжд",
    image: "images/rain.png",
    audio: "audio/rain.mp3",
    hasChildren: false,
  },
  {
    id: "Snow",
    level: 1,
    parent: "Weather",
    english: "Snow",
    bulgarian: "Сняг",
    image: "images/snow.png",
    audio: "audio/snow.mp3",
    hasChildren: false,
  },
  {
    id: "Sun",
    level: 1,
    parent: "Weather",
    english: "Sun",
    bulgarian: "Слънце",
    image: "images/sun.png",
    audio: "audio/sun.mp3",
    hasChildren: false,
  },
  {
    id: "Windy",
    level: 1,
    parent: "Weather",
    english: "Windy",
    bulgarian: "Ветровито",
    image: "images/windy.png",
    audio: "audio/windy.mp3",
    hasChildren: false,
  },
  {
    id: "Day",
    level: 2,
    parent: "When?",
    english: "Day",
    bulgarian: "Ден",
    image: "images/day.png",
    audio: "audio/day.mp3",
    hasChildren: false,
  },
  {
    id: "Morning",
    level: 2,
    parent: "When?",
    english: "Morning",
    bulgarian: "Сутрин",
    image: "images/morning.png",
    audio: "audio/morning.mp3",
    hasChildren: false,
  },
  {
    id: "Night",
    level: 2,
    parent: "When?",
    english: "Night",
    bulgarian: "Нощ",
    image: "images/night.png",
    audio: "audio/night.mp3",
    hasChildren: false,
  },
  {
    id: "Home",
    level: 2,
    parent: "Where?",
    english: "Home",
    bulgarian: "Дом",
    image: "images/home.png",
    audio: "audio/home.mp3",
    hasChildren: false,
  },
  {
    id: "Mira's Room",
    level: 2,
    parent: "Where?",
    english: "Mira's Room",
    bulgarian: "Стаята на Мира",
    image: "images/mirasroom.png",
    audio: "audio/mirasroom.mp3",
    hasChildren: false,
  },
  {
    id: "Aunt Peyton",
    level: 2,
    parent: "Who?",
    english: "Aunt Peyton",
    bulgarian: "Леля Пейтън",
    image: "images/Auntpeyton.png",
    audio: "audio/Auntpeyton.mp3",
    hasChildren: false,
  },
  {
    id: "Baby",
    level: 2,
    parent: "Who?",
    english: "Baby",
    bulgarian: "Бебе",
    image: "images/baby.png",
    audio: "audio/baby.mp3",
    hasChildren: false,
  },
  {
    id: "Cat",
    level: 2,
    parent: "Who?",
    english: "Cat",
    bulgarian: "Котка",
    image: "images/Cat.png",
    audio: "audio/Cat.mp3",
    hasChildren: false,
  },
  {
    id: "Dad",
    level: 2,
    parent: "Who?",
    english: "Dad",
    bulgarian: "Татко",
    image: "images/dad.png",
    audio: "audio/dad.mp3",
    hasChildren: false,
  },
  {
    id: "Dog",
    level: 2,
    parent: "Who?",
    english: "Dog",
    bulgarian: "Куче",
    image: "images/dog.png",
    audio: "audio/dog.mp3",
    hasChildren: false,
  },
  {
    id: "Fish",
    level: 2,
    parent: "Who?",
    english: "Fish",
    bulgarian: "Риба",
    image: "images/Fish.png",
    audio: "audio/Fish.mp3",
    hasChildren: false,
  },
  {
    id: "Grandma",
    level: 2,
    parent: "Who?",
    english: "Grandma",
    bulgarian: "Баба",
    image: "images/grandma.png",
    audio: "audio/grandma.mp3",
    hasChildren: false,
  },
  {
    id: "Grandpa",
    level: 2,
    parent: "Who?",
    english: "Grandpa",
    bulgarian: "Дядо",
    image: "images/grandpa.png",
    audio: "audio/grandpa.mp3",
    hasChildren: false,
  },
  {
    id: "Me",
    level: 1,
    parent: "Who?",
    english: "Me",
    bulgarian: "Аз",
    image: "images/me.png",
    audio: "audio/me.mp3",
    hasChildren: false,
  },
  {
    id: "Mom",
    level: 2,
    parent: "Who?",
    english: "Mom",
    bulgarian: "Мама",
    image: "images/Mom.png",
    audio: "audio/Mom.mp3",
    hasChildren: false,
  },
  {
    id: "Neighbors",
    level: 2,
    parent: "Who?",
    english: "Neighbors",
    bulgarian: "Съседи",
    image: "images/neighbors.png",
    audio: "audio/neighbors.mp3",
    hasChildren: false,
  },
  {
    id: "Uncle Addie",
    level: 2,
    parent: "Who?",
    english: "Uncle Addie",
    bulgarian: "Чичо Ади",
    image: "images/uncleaddie.png",
    audio: "audio/uncleaddie.mp3",
    hasChildren: false,
  },
  {
    id: "Uncle Jasce",
    level: 2,
    parent: "Who?",
    english: "Uncle Jasce",
    bulgarian: "Чичо Джейс",
    image: "images/unclejasce.png",
    audio: "audio/unclejasce.mp3",
    hasChildren: false,
  },
  {
    id: "We",
    level: 1,
    parent: "Who?",
    english: "We",
    bulgarian: "Ние",
    image: "images/we.png",
    audio: "audio/we.mp3",
    hasChildren: false,
  },
  {
    id: "You",
    level: 1,
    parent: "Who?",
    english: "You",
    bulgarian: "Ти",
    image: "images/you.png",
    audio: "audio/you.mp3",
    hasChildren: false,
  },
];
